### ISSUE TITLE
Check if rosdep keys for system packages exist

### ISSUE THREAD

**Issue by jacquelinekay** [ros/rosdistro#11050]
There should be an automated check for rosdep keys to see if they actually exist for the target. Currently rosdep keys can be changed but erroneous keys won't be checked until the package that depends on the key is built.

Checking in a lightweight fashion would be tricky. Because Ubuntu and Debian have web databases, perhaps there is a web API for a package exists in a particular distribution version/architecture combination, e.g. via curl.

**Comment by tfoote** [comment]
Duplicate: https://github.com/ros/rosdistro/issues/1339 

The web api is interesting though we also need to support using our backports repo. There are several apt APIs which can be scripted. And presumably the same can be done for rpms and brew and pip.
