### ISSUE TITLE
ros organization permissions audit

### ISSUE THREAD

**Issue by jacquelinekay** [ros/rosdistro#11150]
As stated in the [email to ros-users](http://lists.ros.org/pipermail/ros-users/2016-April/069965.html), please post in this thread with the permissions you would like to retain for the ros Github organization (ownership and read permissions) before May 2nd.

@ros/owners

**Comment by jonbinney** [comment]
Really, I should never have been trusted with any permissions at all......

**Comment by jonbinney** [comment]
Actually push is useful for me on some repos (filters, for example, which I occasionally release)

**Comment by 130s** [comment]
>  the permissions you would like to retain for the ros Github organization (ownership and read permissions)

Is this ticket specifically for `ros` organization (https://github.com/ros) only, or is it also for `ros-*` orgs?

**Comment by dirk-thomas** [comment]
Closing due to age and inactivity.
