### ISSUE TITLE
Enforce version numbers in rosdistro CI jobs follow best practices

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#11852]
With ompl now released there are no packages which don't follow the recommended versioning pattern. We cannot make catkin_pkg more strict for it might break non-standard rules. But we can enforce it in the rosdistro index that if you want to be indexed we can enforce it. 

This should be added to the Pull Request verification checks.

Replaces: https://github.com/ros-infrastructure/catkin_pkg/issues/140

**Comment by mikaelarguedas** [comment]
this has been addressed in #15774
