### ISSUE TITLE
Literate_pr2 stack- Required.

### ISSUE THREAD

**Issue by Telpr2** [ros/rosdistro#12799]
Hi,
  We are working with PR2. would like to get literate_pr2 stack so that we can make PR2 read text using kinect. Unable to get the code from  "https://mediabox.grasp.upenn.edu/svn/penn-ros-pkgs/literate_pr2/trunk". Can you please provide us with the code. Thanks a lot. Awaiting your earliest response.
Thanks and Regards,
PR2 Team

**Comment by dirk-thomas** [comment]
The doc entry of `literate_pr2` is from ROS Electric which is a long time ago (https://github.com/ros/rosdistro/blob/da50ae4bf7f80cd11d8512cad3d094d828b00d07/doc/electric/penn-ros-pkg.rosinstall#L6). The owner and maintainers of that code are not related to this repository at all and we don't have any knowledge about this server.

You might want to search for the creators of that software and try to contact them directly. One starting point might be their video which contains names: http://wiki.ros.org/literate_pr2
