### ISSUE TITLE
ROS encryption

### ISSUE THREAD

**Issue by mat-l** [ros/rosdistro#12899]
Hi all,

I have a very general question about ROS and its messaging system.
Is there any chance to communicate between nodes, services and so on in a encrypted way that no external person/software can sniff on data which is problished by the ROS participants?

Regrads
matl

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.
