### ISSUE TITLE
Kinetic : apt-get installation of ros-kinetic-desktop-full throws openni / libpcl errors 

### ISSUE THREAD

**Issue by katanachan** [ros/rosdistro#12950]
Errors were encountered while processing:
 libopenni0
 libopenni-dev
 openni-utils
 libopenni-sensor-pointclouds0
 libpcl-io1.7:amd64
 libpcl-visualization1.7:amd64
 libpcl1.7
 libpcl-dev
 ros-kinetic-pcl-conversions
 ros-kinetic-pcl-ros
 ros-kinetic-perception-pcl
 ros-kinetic-perception
 ros-kinetic-desktop-full

dpkg: error processing package ros-kinetic-perception-pcl (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already

I had to solve the issue by removing all my libopenni-dev and libpcl-1.7 packages and then re-installing ros-kinetic-desktop from scratch.

**Comment by tfoote** [comment]
It sounds like you've solved your problem, there was some sort of conflict. If you want to debug you'll want to review all the packages that you uninstalled to find what conflicted. 

If you'd like help debugging this please ask on http://answers.ros.org When you ask there please provide more information that can answer as much of the below as possible. 

- Can you provide instructions how to reproduce your problem? 
- What platform/arch are you running on? 
- What are your apt sources?
- Have you installed anything out of band?
- It looks like libopenni-dev was part of your failed installation did you already have a different version?
- rerun your attempted installation with the option `-o Debug::pkgProblemResolver=yes` and show the output.
