### ISSUE TITLE
Lunar Check Wiki pages

### ISSUE THREAD

**Issue by mikaelarguedas** [ros/rosdistro#13677]
Replaced by list in https://github.com/ros/rosdistro/issues/13677#issuecomment-303569389

**Comment by mikaelarguedas** [comment]
List of page using "rosversion kinetic"
- [ ] http://wiki.ros.org/rosjava/Tutorials
- [ ] http://wiki.ros.org/Installation/UbuntuARM/
- [ ] http://wiki.ros.org/kobuki/Tutorials/Installation/
- [ ] http://wiki.ros.org/kobuki/Tutorials/Installation/
- [ ] http://wiki.ros.org/kobuki/Tutorials/Installation/
- [ ] http://wiki.ros.org/kobuki/Tutorials/Installation/
- [ ] http://wiki.ros.org/android/Tutorials/
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/Xbot
- [ ] http://wiki.ros.org/Robots/MRP2
- [ ] http://wiki.ros.org/Robots/MRP2
- [ ] http://wiki.ros.org/Robots/MRP2
- [ ] http://wiki.ros.org/Installation/Ubuntu
- [ ] http://wiki.ros.org/Robots/qbmove
- [ ] http://wiki.ros.org/Robots/qbmove
- [ ] http://wiki.ros.org/Robots/qbmove
- [ ] http://wiki.ros.org/perception_oru
- [ ] http://wiki.ros.org/Robots/qbhand
- [ ] http://wiki.ros.org/Robots/qbhand
- [ ] http://wiki.ros.org/Robots/qbhand
- [ ] http://wiki.ros.org/Robots/qbhand
- [ ] http://wiki.ros.org/rviz/Tutorials/Librviz(3a20)Incorporating(20)RViz(20)into(20)a(20)Custom(20)GUI
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/ROSARIA/Tutorials/How(20)to(20)use(20)ROSARIA
- [ ] http://wiki.ros.org/motoman_experimental
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/hansbot/Tutorials
- [ ] http://wiki.ros.org/pioneer_bringup
- [ ] http://wiki.ros.org/pioneer_bringup
- [ ] http://wiki.ros.org/pioneer_bringup
- [ ] http://wiki.ros.org/pioneer_bringup
- [ ] http://wiki.ros.org/pioneer_bringup
- [ ] http://wiki.ros.org/pioneer_bringup
- [ ] http://wiki.ros.org/fanuc
- [ ] http://wiki.ros.org/visp
- [ ] http://wiki.ros.org/rosjava
- [ ] http://wiki.ros.org/rosjava
- [ ] http://wiki.ros.org/rosjava
- [ ] http://wiki.ros.org/rosjava
- [ ] http://wiki.ros.org/rosjava
- [ ] http://wiki.ros.org/rosjava
- [ ] http://wiki.ros.org/rosjava
- [ ] http://wiki.ros.org/Robots/evarobot
- [ ] http://wiki.ros.org/Installation/Slackware
- [ ] http://wiki.ros.org/android
- [ ] http://wiki.ros.org/android
- [ ] http://wiki.ros.org/android
- [ ] http://wiki.ros.org/android
- [ ] http://wiki.ros.org/ShadowRepository
- [ ] http://wiki.ros.org/ShadowRepository
- [ ] http://wiki.ros.org/Installation/Source
- [ ] http://wiki.ros.org/kuka_experimental
- [ ] http://wiki.ros.org/rviz/Tutorials/Plugins(3a20)New(20)Dockable(20)Panel
- [ ] http://wiki.ros.org/dynamixel_workbench
- [ ] http://wiki.ros.org/Installation/Gentoo
- [ ] http://wiki.ros.org/sick_tim
- [ ] http://wiki.ros.org/sick_tim
- [ ] http://wiki.ros.org/sick_tim
- [ ] http://wiki.ros.org/sick_tim
- [ ] http://wiki.ros.org/sick_tim
- [ ] http://wiki.ros.org/fanuc_driver
- [ ] http://wiki.ros.org/ariac/Tutorials/MoveItInterface
- [ ] http://wiki.ros.org/ariac/Tutorials/MoveItInterface
- [ ] http://wiki.ros.org/ariac/Tutorials/MoveItInterface
- [ ] http://wiki.ros.org/ariac/Tutorials/MoveItInterface
- [ ] http://wiki.ros.org/ariac/Tutorials/MoveItInterface
- [ ] http://wiki.ros.org/ariac/Tutorials/MoveItInterface
- [ ] http://wiki.ros.org/ariac/Tutorials/MoveItInterface
- [ ] http://wiki.ros.org/ariac/Tutorials/MoveItInterface
- [ ] http://wiki.ros.org/Installation/Debian
- [ ] http://wiki.ros.org/Robots/TurtleBot
- [ ] http://wiki.ros.org/Robots/TurtleBot
- [ ] http://wiki.ros.org/Robots/TurtleBot
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/ariac/Tutorials/SystemSetup
- [ ] http://wiki.ros.org/robot_localization
- [ ] http://wiki.ros.org/robot_localization
- [ ] http://wiki.ros.org/robot_localization
- [ ] http://wiki.ros.org/robot_localization
- [ ] http://wiki.ros.org/robot_localization
- [ ] http://wiki.ros.org/robot_localization
- [ ] http://wiki.ros.org/robot_localization
- [ ] http://wiki.ros.org/rviz/Tutorials/Plugins(3a20)New(20)Tool(20)Type
- [ ] http://wiki.ros.org/rviz/Tutorials/Plugins(3a20)New(20)Display(20)Type
- [ ] http://wiki.ros.org/Robots/evarobot/tr
- [ ] http://wiki.ros.org/ariac/Tutorials/SensorInterface
- [ ] http://wiki.ros.org/ariac/Tutorials/SensorInterface

**Comment by dirk-thomas** [comment]
The list needs to be deduplicated.

**Comment by mikaelarguedas** [comment]
all these have been updated and the missing one have been ticketed and adressed : https://github.com/rosjava/android_core/issues/269.
Closing this
