### ISSUE TITLE
Inconsistent rosdep for key fltk

### ISSUE THREAD

**Issue by meyerj** [ros/rosdistro#1389]
rosdep key `fltk` resolves to `[fluid, libfltk1.1-dev]` for Ubuntu since 21f94b840117fc48f0dd74727b97095c1a0ede93. Package [fluid](http://packages.ubuntu.com/precise/fluid) recommends [libfltk1.3-dev](http://packages.ubuntu.com/precise/libfltk1.3-dev) in Ubuntu precise, which is incompatible with [libfltk1.1-dev](http://packages.ubuntu.com/precise/libfltk1.1-dev) required by rosdep.

Although this is not really a conflict as libfltk1.3-dev is only a recommendation, it obviously causes errors on Hudson, e.g.
- http://build.willowgarage.com/job/devel_groovy_hector_quadrotor_precise_amd64/15/ or
- http://build.willowgarage.com/view/devel_groovy/job/devel_groovy_hector_gazebo_precise_amd64/21/.

I cannot reproduce this result locally, but I assume that apt is somehow configured to always install recommended packages and even to allow removal of conflicting packages on the build servers.

See also ros-infrastructure/jenkins_scripts#46.

**Comment by tfoote** [comment]
Reviewing this it seems that 1.3 is now the recommended one. We should update the rule to point to 1.3 for newer versions. I don't want to break anything already running so my suggestion would be to make the change for vivid and forward. Leaving the older systems as they are.

**Comment by dirk-thomas** [comment]
Why not also for utopic?

**Comment by tfoote** [comment]
Good point I was thinking about utopic already being out. but we haven't released ROS on top yet so that should be fine.

**Comment by deffi** [comment]
Now calling rosdep install (as described on [indigo/Installation/Source](http://wiki.ros.org/indigo/Installation/Source)) alternatingly installs `libfltk1.3-dev` and `libfltk1.1-dev`, and uninstalls the other.

Adding the following line to a local rosdep YAML file resolves the issue, only installing 1.3:
`fltk: { ubuntu: { utopic: ["fluid", "libfltk1.3-dev"] } }`

In fact, looking at [rosdistro/rosdep/base.yaml](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml) reveals that the fix (9fd2c55c0f6ef5957d18160f43e7af25b45a7015) sets the correct version for `libfltk-dev`, but `fltk` still refers to `libfltk1.1-dev` on all Ubuntu versions.
