### ISSUE TITLE
kinetic job reconfiguration is failing

### ISSUE THREAD

**Issue by hrnr** [ros/rosdistro#14360]
Hi,

kinetic jobs reconfiguration task `Krel_reconfigure-jobs` is failing since Mar 23 due to circular dependecies between `roch_bringup, roch_capabilities`. This was introduced by #14299. This prevents releasing new packages for kinetic.

Is anybody aware of it?

Cheers,
Jiri

**Comment by dirk-thomas** [comment]
@tfoote is in charge of Kinetic and has received notification email for all of the failing jobs. Please also improve the unit tests in this repo to catch the problem before merging in the future.

**Comment by dirk-thomas** [comment]
The same is obviously the case for Indigo.

**Comment by tfoote** [comment]
Also at issue:
Indigo: https://github.com/ros/rosdistro/pull/14268
Debinc: https://github.com/ros/rosdistro/pull/14306

**Comment by tfoote** [comment]
Kinetic reconfiguring is running, and Indigo is waiting for kinetic to finish to run. I think it should work after kinetic finishes. I'll check in the morning.

**Comment by tfoote** [comment]
Indigo and Kinetic are both reconfiguring successfully now.
