### ISSUE TITLE
Validation of new releases on travis does not catch circular dependencies

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#14373]
This can caused merged PRs to prevent the farm from reconfiguring. Such as #14360 

It would be great to catch this CI tests before we merge a new release PR.

**Comment by dirk-thomas** [comment]
Since this is breaking the buidlfarm when it happens I consider it to be quite important to get added to the tests. @tfoote Are you planning to implement this test?

**Comment by dirk-thomas** [comment]
Since I think this is a pretty crucial I implemented the unit test in #14385.
