### ISSUE TITLE
MacOS Sierra - fail to install ros indigo at gazebo

### ISSUE THREAD

**Issue by DinnerHowe** [ros/rosdistro#14416]
hi, all:
 I followed the official installation of ROS Indigo on OSX at: http://wiki.ros.org/indigo/Installation/OSX/Homebrew/Source

 however it failed when I tried to install it `rosdep install --from-paths src --ignore-src --rosdistro indigo -y`

 the error is :

```
executing command [brew install gazebo]
==> Installing gazebo1 from osrf/simulation
qt4-no-webkit: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
ERROR: the following rosdeps failed to install
  homebrew: command [brew install gazebo] failed
```
while I tried install qt4 but I failed again. (this is how I solved qt problem: https://github.com/mikepurvis/ros-install-osx/issues/63)

so, if anyone could help me solve this issue?
thanks advanced
regards

**Comment by wjwwood** [comment]
Unfortunately I believe ROS Indigo on macOS is now a dead-end because Homebrew no longer provides Qt4 Formula, see:

http://answers.ros.org/question/262399/os-x-indigo-212-and-213-install-problems/?answer=262407#post-id-262407
