### ISSUE TITLE
ur_modern_driver repo unaccessable

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#14522]
The ur_modern_driver source repo is not available from https://github.com/TheDash/ur_modern_driver.git

As indicated in #11474 by @TheDash 

I found a repo with the same name at: https://github.com/ThomasTimm/ur_modern_driver @ThomasTimm is this the same?

**Comment by ThomasTimm** [comment]
I don't know if it is exactly the same, but my repo is the original and what is recommended to use by ros-Industrial until we get it merged.

**Comment by tfoote** [comment]
Thanks I've updated the url in #14565
