### ISSUE TITLE
Add gentoo to rosdep yaml documentation

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/rosdistro#15087]
Gentoo is missing from here

http://docs.ros.org/independent/api/rosdep/html/rosdep_yaml_format.html#rosdep-yaml

Gentoo main package manager is portage, but there are also paludis and pkgcore, avoid pip if possible (or only for non colliding packages).

**Comment by mikaelarguedas** [comment]
thanks for pointing it out, please submit  PR to the [rosdep documentation](https://github.com/ros-infrastructure/rosdep/blob/master/doc/rosdep_yaml_format.rst)

Given that the documentation is not hosted here I'm going to close this

**Comment by Alessandro-Barbieri** [comment]
Thanks
