### ISSUE TITLE
Missing Dependencies for Gentoo Linux

### ISSUE THREAD

**Issue by allenh1** [ros/rosdistro#15082]
Here's the list from my script:

 * [ ] disper
 * [ ] dkms
 * [ ] g++-static
 * [ ] gstreamer0.10-pocketsphinx
 * [ ] ipython
 * [ ] language-pack-de
 * [ ] language-pack-en
 * [ ] leg_detector
 * [ ] libcap-dev
 * [ ] libcoin80-dev
 * [ ] libesd0-dev
 * [ ] libfreenect-dev
 * [ ] mapnik-utils
 * [ ] mrpt
 * [ ] nodejs-legacy
 * [ ] npm
 * [ ] opende
 * [ ] people_velocity_tracker
 * [ ] python-argcomplete
 * [ ] python-argh
 * [ ] python-avahi
 * [ ] python-bloom
 * [ ] python-bs4
 * [ ] python-bson
 * [ ] python-catkin-lint
 * [ ] python-catkin-tools
 * [ ] python-chainer-pip
 * [ ] python-cheetah
 * [ ] python-cherrypy
 * [ ] python-click
 * [ ] python-colorama
 * [ ] python-concurrent.futures
 * [ ] python-couchdb
 * [ ] python-crypto
 * [ ] python-dateutil
 * [ ] python-dlib
 * [ ] python-docutils
 * [ ] python-enum34
 * [ ] python-expiringdict
 * [ ] python-fcn-pip
 * [ ] python-flask
 * [ ] python-gdown-pip
 * [ ] python-gi
 * [ ] python-gst
 * [ ] python-h5py
 * [ ] python-mapnik
 * [ ] python-mechanize
 * [ ] python-oauth2
 * [ ] python-omniorb
 * [ ] python-percol
 * [ ] python-pip
 * [ ] python-progressbar
 * [ ] python-pygame
 * [ ] python-pygithub3
 * [ ] python-pymongo
 * [ ] python-pytest
 * [ ] python-pyudev
 * [ ] python-requests
 * [ ] python-rosdistro
 * [ ] python-rosinstall
 * [ ] python-serial
 * [ ] python-simplejson
 * [ ] python-singledispatch
 * [ ] python-six
 * [ ] python-skimage
 * [ ] python-sklearn
 * [ ] python-slacker-cli
 * [ ] python-sqlalchemy
 * [ ] python-sympy
 * [ ] python-tabulate-pip
 * [ ] python-termcolor
 * [ ] python-texttable
 * [ ] python-tilestache
 * [ ] python-tk
 * [ ] python-twisted-core
 * [ ] python-tz
 * [ ] python-waitress
 * [ ] python-webob
 * [ ] python-websocket
 * [ ] python-wstool
 * [ ] python-zmq
 * [ ] qtmobility-dev
 * [ ] sr_moveit_config
 * [ ] thormang3_action_script_player
 * [ ] thormang3_foot_step_generator
 * [ ] thormang3_offset_tuner_client
 * [ ] xfonts-100dpi
 * [ ] xfonts-75dpi
 * [ ] xvfb

**Comment by allenh1** [comment]
@Alessandro-Barbieri do you want to work on this?

**Comment by mikaelarguedas** [comment]
is it possible to generate a list of the missing keys for all ROS distros and removing duplicates? that would be easier to process IMO

**Comment by allenh1** [comment]
Sure. One moment.

**Comment by Alessandro-Barbieri** [comment]
@allenh1 yess

**Comment by allenh1** [comment]
Updating the original list.

**Comment by Alessandro-Barbieri** [comment]
I see `openssl`, there is a problem: how to implement this?
```
ssl? (
    !libressl? ( dev-libs/openssl:0= )
    libressl? ( dev-libs/libressl:0= )
)
```

see https://wiki.gentoo.org/wiki/Project:LibreSSL for reference

**Comment by Alessandro-Barbieri** [comment]
If you merge my pull request some of them will go away or will be done all in one commit?

**Comment by Alessandro-Barbieri** [comment]
Another question: there is a way to practically edit that huge `yaml` files?

**Comment by allenh1** [comment]
You certainly need not remove them all in one commit. I'll update the list as we go. I removed a whole lot of packages that didn't need to be in the list already. If you want to hold off, I'll modify the thing generating the ebuilds so that it gives one list at the very end for all relevant distros. The current list is a little daunting.

**Comment by allenh1** [comment]
For the `openssl` issue, that's a serious problem... Hm... Maybe for now we just put `dev-libs/openssl` until I come up with a better way of handling this. 

Perhaps it would be good to write a small `virtual/ssl` ebuild to put in the repo that installs one of those, as conditioned there.

@mikaelarguedas  thoughts?

**Comment by allenh1** [comment]
@Alessandro-Barbieri I'm working on shortening that list for us, don't worry. I'm generating just what would be needed to do indigo, kinetic and lunar. It'll be about half an hour to process this.

**Comment by Alessandro-Barbieri** [comment]
Python and ruby ready to be merged.

**Comment by allenh1** [comment]
@Alessandro-Barbieri Updated the list

**Comment by allenh1** [comment]
List now only contains those necessary for lunar & kinetic to have all deps satisfied.

**Comment by allenh1** [comment]
Updated to add the deps for indigo. The list is now complete.

**Comment by allenh1** [comment]
@Alessandro-Barbieri please reference this issue in any related PR's.

**Comment by Alessandro-Barbieri** [comment]
What to do with the `*-pip` packages?

**Comment by allenh1** [comment]
Pip is not supported anymore, so I don't think they need to be implemented. Just the list above is necessary.

**Comment by Alessandro-Barbieri** [comment]
For the openssl thing, the libressl overlay provide a fake `openssl` package that is co-installable with `libressl` so no need for a  virtual an we'll use `openssl`.

**Comment by mikaelarguedas** [comment]
> What to do with the *-pip packages?

pip is supported for people building their packages from source and using rosdep to install their dependencies. But is not used by the buildfarm, meaning that every **released** package doesn't use any `-pip` key. So I think it's safe to not add them for now and keep this list more digestible

**Comment by Alessandro-Barbieri** [comment]
Finished, time to check missing packages @allenh1

**Comment by Alessandro-Barbieri** [comment]
Do you update the list manually or with a script?

**Comment by allenh1** [comment]
I update them manually

**Comment by allenh1** [comment]
But it's probably easier to just replace this list with an updated one when the changes are merged.

**Comment by Alessandro-Barbieri** [comment]
Can you rebuild the list?

**Comment by allenh1** [comment]
Yes, kinetic is rebuilding atm.

**Comment by allenh1** [comment]
> Can you rebuild the list?

Done.

**Comment by mikaelarguedas** [comment]
Note: There seem to be some ROS packages and some pip keys in the new list that can be ignored

**Comment by Alessandro-Barbieri** [comment]
Ignoring python for now

    `disper` in overlay https://bugs.gentoo.org/show_bug.cgi?id=281024
    `dkms` in overlay https://bugs.gentoo.org/show_bug.cgi?id=100754
    `g++-static` `sys-devel/gcc`
    `gstreamer0.10-pocketsphinx` `app-accessibility/pocketsphinx`
    `language-pack-de` ubuntu only package
    `language-pack-en` ubuntu only package
    leg_detector
    libcap-dev
    libcoin80-dev
    libesd0-dev
    libfreenect-dev
    mapnik-utils
    mrpt
    nodejs-legacy
    npm
    opende
    people_velocity_tracker
    qtmobility-dev
    sr_moveit_config
    thormang3_action_script_player
    thormang3_foot_step_generator
    thormang3_offset_tuner_client
    xfonts-100dpi
    xfonts-75dpi
    xvfb

**Comment by mikaelarguedas** [comment]
All the "what is this?" are ROS packages and thus can be removed from the list

**Comment by leio** [comment]
xfonts-100dpi is probably media-fonts/font-bitstream-100dpi
xfonts-75dpi is probably font-bitstream-75dpi
But we install in /usr/share/fonts prefix, not /usr/share/fonts/X11 like debian; and I don't see any ISO-8859-* files like debian filelist lists

**Comment by Alessandro-Barbieri** [comment]
> and I don't see any ISO-8859-* files like debian filelist lists

These are in the `media-fonts/font-adobe-100dpi` and `media-fonts/font-adobe-75dpi`

**Comment by Alessandro-Barbieri** [comment]
@leio thanks

**Comment by Alessandro-Barbieri** [comment]
How can I know which ros packages pulls in these dependencies?

**Comment by allenh1** [comment]
@Alessandro-Barbieri You can run my script and watch the output of it (it shows up in red when things fail to resolve).

**Comment by tfoote** [comment]
@allenh1 Can we close this now that ros-overlay is generally running?

**Comment by allenh1** [comment]
@tfoote sure. That's reasonable.
