### ISSUE TITLE
webkit_dependency: No definition of [python-qt5-bindings-webkit] for OS [osx]

### ISSUE THREAD

**Issue by teancake** [ros/rosdistro#15117]
Hi, I tried to install ros kinetic on **MacOS** by following http://wiki.ros.org/kinetic/Installation/OSX/Homebrew/Source. After executing

`rosdep install --from-paths src --ignore-src --rosdistro kinetic -y`

I got an error message
> RROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> webkit_dependency: No definition of [python-qt5-bindings-webkit] for OS [osx]

I was aware of issue #15088  and I was not using sudo apart from `sudo -H rosdep init`. My system information is as follows
> Darwin abc.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
> Python 2.7.13
> pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
> pyqt-5.8.2 already installed

Could anyone help to figure out what my problem is? Thanks a lot.

**Comment by mikaelarguedas** [comment]
Indeed there is no rule for this package for Mac OS in the rosdep database. If there is an equivalent package in homebrew please submit a PR to https://github.com/ros/rosdistro/blob/master/rosdep/osx-homebrew.yaml to add it (contributing guide available [here](http://docs.ros.org/independent/api/rosdep/html/contributing_rules.html)). If these bindings are already part of pyqt5 in homebrew please create an entry for it referencing pyqt5 like it's done for [the other bindings](https://github.com/ros/rosdistro/blob/master/rosdep/osx-homebrew.yaml#L599-L602)

**Comment by canlang** [comment]
Thanks,
