### ISSUE TITLE
Add python-tqdm

### ISSUE THREAD

**Issue by cglwn** [ros/rosdistro#15561]
We use [tqdm](https://github.com/tqdm/tqdm) for progress bars in Python for loops.

It is in Debian, Fedora, and Ubuntu (after Yakkety) repositories and PyPI for older Ubuntu versions.
[Debian](https://packages.debian.org/sid/python/python-tqdm)
[Fedora](https://admin.fedoraproject.org/pkgdb/package/rpms/python-tqdm/)
[Ubuntu](https://packages.ubuntu.com/yakkety/python-tqdm)
[PyPI](https://pypi.python.org/pypi/tqdm)

**Comment by Alessandro-Barbieri** [comment]
[gentoo](https://packages.gentoo.org/packages/dev-python/tqdm)

**Comment by tfoote** [comment]
Fixed in #15562
