### ISSUE TITLE
Add yapf

### ISSUE THREAD

**Issue by cglwn** [ros/rosdistro#15566]
This is a Python code formatter that I would like my team to use, distributing through rosdep would make this easier.
 
[Debian (Jesse Backports, Buster)](https://packages.debian.org/search?keywords=yapf)
[Ubuntu (Zesty and Artful)](https://packages.ubuntu.com/search?keywords=yapf)
[PyPI](https://pypi.python.org/pypi/yapf)

Fedora package will exist with google/yapf/issues/67.

**Comment by dirk-thomas** [comment]
Please create a PR for this.

**Comment by cglwn** [comment]
Just made one.

**Comment by dirk-thomas** [comment]
In the future just go ahead and create the PR - no need for a duplicate issue. I will close this one in favor of the PR.

**Comment by cglwn** [comment]
Noted, thanks.
