### ISSUE TITLE
Users who submit PRs to this repo are getting flagged "Abuse detected" by travis

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#16337]
This manifests itself in that it looks like the CI tests from travis never finish. They actually never start. 

They can be seen here: https://travis-ci.org/ros/rosdistro/requests

We have contacted Travis CI support in the past and they have either manually cleared the flag, and also advised that the user log into travis-ci.org so that they can verify the user somehow. 

I'm creating this to be a place to collect references and hopefully provide people with a solution. If you have to do the above login please comment here. 

Instances already observed include: #16335 #16186 #16299 #15650

**Comment by tfoote** [comment]
Several of these have been first time contributors. However #16335 is particularly odd in that @peci1  successfully submitted a PR a few hours earlier.

**Comment by peci1** [comment]
I logged in to travis. What next?

**Comment by tfoote** [comment]
@peci1 I closed and reopened your PR and it's running the tests now.

**Comment by tfoote** [comment]
I heard back from Travis CI Support and they don't have a workaround for this in the short term. They are aware of the pain and are working on a longer term solution. So I'll leave this open for visibility. If you have this problem when submitting to rosdistro please try logging into travis and then close and reopen the PR to retrigger travis as well as comment here on whether it works or doesn't work.

**Comment by tfoote** [comment]
Hit by @YoshihiroMIYAKOSHI in #16536 
![image](https://user-images.githubusercontent.com/447804/33680245-d760ef58-da75-11e7-9c4e-5671e7cf66e1.png)

**Comment by tfoote** [comment]
We haven't had any reports of this in a year, so I'm going to close this.

**Comment by emersonknapp** [comment]
I logged in to travis, closed the PR, opened the PR, and got the same result the second time

https://github.com/ros/rosdistro/pull/21834
