### ISSUE TITLE
Can't install robot variant on raspbian Jessie

### ISSUE THREAD

**Issue by deb0ch** [ros/rosdistro#16592]
I tried to follow [the official guide for installing Kinetic on Raspbian Jessie](http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi) to install the robot variant, and the following missing dependency make the installation of the entire workspace fail:

```
$ rosdep install -y --from-paths src --ignore-src --rosdistro kinetic -r --os=debian:jessie
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
collada_urdf: No definition of [collada-dom] for OS version [jessie]
collada_parser: No definition of [collada-dom] for OS version [jessie]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
Tried to install collada-dom using apt:
```

sudo apt-get install libcollada-dom2.4-dp-dev
but did nothing.

Also tried instructions from https://answers.ros.org/question/194645/indigo-on-raspberrydebian-dependency-problem-catkin-error/:

```
cd ~/ros_catkin_ws/external_src
sudo apt-get install libboost-filesystem-dev libxml2-dev
wget http://downloads.sourceforge.net/project/collada-dom/Collada%20DOM/Collada%20DOM%202.4/collada-dom-2.4.0.tgz
tar -xzf collada-dom-2.4.0.tgz
cd collada-dom-2.4.0
cmake .
# ***downgrade gcc***
sudo make install
```

Install successful, but `rosdep` still has the same error.

What should I do ?

**Comment by tfoote** [comment]
collada is manually packaged for jessie, and as you've seen raspbian is not one of our standard architectures. If you've manually installed the rosdep contents you should use the rosdep option `--skip-key` to allow it to assume that the key is resolved and it can continue without error.
