### ISSUE TITLE
libqwt-dev misses QT5 for xenial and above

### ISSUE THREAD

**Issue by samuelba** [ros/rosdistro#19566]
@pgorczak  Commit https://github.com/ros/rosdistro/commit/25747529d24ca067c148149cb6c6fc34f676be84 broke the rosdep key `libqwt-dev` for rqt_multiplot. Since releases for xenial and above will need QT5. Either these changes should be reverted or we have to add a new key like  `libqwt-qt5-dev` as suggested by https://github.com/ros/rosdistro/issues/19394 .

**Comment by pgorczak** [comment]
This happened due to https://github.com/ros/rosdistro/pull/19327 and https://github.com/ros/rosdistro/pull/19329 where we decided to not switch to Qt5 under the hood for xenial and above. I think your PR https://github.com/ros/rosdistro/pull/19567 is the way to go.

**Comment by samuelba** [comment]
Fixed with pull request https://github.com/ros/rosdistro/pull/19567
