### ISSUE TITLE
python package python-pkg-resources has merged into setuptools

### ISSUE THREAD

**Issue by russkel** [ros/rosdistro#21424]
Another note for deprecation at some point, pkg-resources seems to not be a separate package any more and is included in setuptools.

**Comment by tfoote** [comment]
Your statement appears to be true for the source package, but Debian packages it separately so the package appears to be valid and available in the binary packages including the upcoming LTS focal. https://packages.ubuntu.com/focal/python-pkg-resources 

https://packages.ubuntu.com/search?keywords=python-pkg-resources

Please consider opening a PR with a requested change, but as it looks for now the rosdep key appears to be what we want.
