### ISSUE TITLE
Can you include the Python package noise?

### ISSUE THREAD

**Issue by nbro** [ros/rosdistro#22572]
Can you include the Python package [noise](https://pypi.org/project/noise/), so that it can be installed with `rosdep` or specified in the `package.xml` as e.g. a build dependency like `<build_depend>python-noise</build_depend>`?

**Comment by tfoote** [comment]
It is possible to do so. Please open a pull request to propose adding them.

Guidelines for contributing can be found here: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md
