### ISSUE TITLE
Bug in advertise_service_options.h

### ISSUE THREAD

**Issue by withocola** [ros/rosdistro#22978]
In line 66 "service.c_str()" is used, but "service" is declared in line 70 "service = _service;". So on Error no name is displayed.

**Comment by tfoote** [comment]
That file does not appear to be in this repository. Please find the appropriate repository for that package on https://index.ros.org/ by searching for the package by name and it will link you to the appropriate tracker. Please also include the distribution and installation method which you're using as well.
