### ISSUE TITLE
ubuntu 18, ros melodic, boost: mutex lock failed in pthread_mutex_lock

### ISSUE THREAD

**Issue by darrahts** [ros/rosdistro#23327]
Today ros did something very strange, roscore wouldnt start (I can't reproduce the error at this point), tried reinstalling it and with a very simple example code I got the error
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)

```
Tried reinstalling it again and was stuck in a package depends - broken - held loop for about 2 hours... Then, Taking a more extreme approach, I completely uninstalled ros with 

```
sudo apt-get remove --purge ros-* -y
sudo apt-get remove --purge python-ros* -y
sudo rm /etc/ros -rf
sudo rm /etc/apt/sources.list.d/ros-latest.list
sudo rm /home/$USER/.ros -rf
sudo apt-get autoremove
//updated ~/.bashrc
```
then, following the instructions on http://wiki.ros.org/melodic/Installation/Ubuntu, and using aptitude instead of apt-get, 
```
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo aptitude install ros-melodic-desktop-full
//update bashrc
sudo rosdep init
rosdep update
roscore
```
perfect! it runs. turtlesim? Also runs! my package? Nope! Same error again.

here is my very simple code (from udemy, I am learning):
```

#include "ros/ros.h"
#include "geometry_msgs/Twist.h"
#include "turtlesim/Pose.h"
#include <sstream>

using namespace std;

ros::Publisher twist_pub;
ros::Subscriber pose_sub;
turtlesim::Pose turtlesim_pose;

void pose_callback(const turtlesim::Pose::ConstPtr & pose_msg)
{
    turtlesim_pose.x = pose_msg->x;
    turtlesim_pose.y = pose_msg->y;
    turtlesim_pose.theta = pose_msg->theta;
}


double deg2rad(double angle)
{
    return angle * 3.141593 / 180.0;
}

void move(double speed, double distance)
{
    geometry_msgs::Twist mv_cmd;

    mv_cmd.linear.x = speed;
    mv_cmd.linear.y = 0;
    mv_cmd.linear.z = 0;

    mv_cmd.angular.x = 0;
    mv_cmd.angular.y = 0;
    mv_cmd.angular.z = 0;

    double t0 = ros::Time::now().toSec();
    double t1 = ros::Time::now().toSec();
    ros::Rate loop_rate(20);
    double current_distance = 0;
    while(current_distance < distance)
    {
        twist_pub.publish(mv_cmd);
        t1 = ros::Time::now().toSec();
        current_distance = speed * (t1-t0);
        ros::spinOnce();
        loop_rate.sleep();
    }
    mv_cmd.linear.x = 0.0;
}

void rotate_absolute(double theta)
{
    double theta_hat = theta - turtlesim_pose.theta;
}

void rotate(double omega_dot, double omega)
{
    geometry_msgs::Twist trn_cmd;

    trn_cmd.linear.x = 0;
    trn_cmd.linear.y = 0;
    trn_cmd.linear.z = 0;

    trn_cmd.angular.x = 0;
    trn_cmd.angular.y = 0;
    trn_cmd.angular.z = omega_dot;


    double t0 = ros::Time::now().toSec();
    double t1 = t0;
    double omega0 = 0;
    ros::Rate loop_rate(20);
    while(omega0 < omega)
    {
        twist_pub.publish(trn_cmd);
        t1 = ros::Time::now().toSec();
        omega0 = omega_dot *(t1-t0);
        ros::spinOnce();
        loop_rate.sleep();
    }
    trn_cmd.angular.z = 0;
    twist_pub.publish(trn_cmd);
}

int main(int argc, char **argv)
{
    ros::init(argc, argv, "robot_cleaner");
    ros::NodeHandle n;

    double speed;
    double distance;
    double omega_dot;
    double omega;

    twist_pub = n.advertise<geometry_msgs::Twist>("/turtle1/cmd_vel", 10);
    pose_sub = n.subscribe("/turtle1/pose", 10, pose_callback);

    cout << "enter speed: ";
    cin >> speed;
    cout << "enter distance: ";
    cin >> distance;
    move(speed, distance);

    cout << "enter angular velocity(deg/s): ";
    cin >> omega_dot;
    cout << "enter angle: ";
    cin >> omega;

    rotate(deg2rad(omega_dot), deg2rad(omega));

}
```
I tested other simple programs and all of them now have since required modification and to some extent still dont work correctly. This is all from code that was working a few days ago. I am not using an active conda environment in any of my terminals either. Things like `user_input = input("your input: ")` had to be changed to `raw_input`, etc. This is a fresh ubuntu install (< 1 week). The only thing I have recently done is install cuda, opencv, and anaconda.

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

You also appear to have two or 3 different questions intermingled here. One is about a traceback one is installing and one is python related.

Make sure to included full instructions for how to reproduce your problem. Mentioning a udemy course that most of us have never seen is not enough to understand what you're doing. Please copy and paste the raw console outputs of your commands and the errors. Saying that things "don't work" or the equivalent means that we have to guess at what didn't work. Include what they do and what you expect them to do as well as what's different.
