### ISSUE TITLE
Can't find dependency although existing in yaml-file.

### ISSUE THREAD

**Issue by tylernewnoise** [ros/rosdistro#23341]
On Ubuntu 16.04 I tried to install yapf via rosdep but rosdep can't find the package although it exists in [python.yaml](https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml) (line 5754). Although it works if I change the order of the yaml files in `/etc/ros/rosdep/sources.list.d/20-default.list`. 
Please note that yapf also exits in [base.yaml](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml), but not for Ubuntu Xenial. I guess the search-algorithm for the package stops too early.

**Comment by tfoote** [comment]
The rules are explicitly evaluated in order and go based on the first match to allow custom overrides of the values on system administrators or users.

It looks like #22073 was added without consolidating with #15567 

These should be consolidated to leverage the pip values for older platforms and binary packages where available. @tylernewnoise Could you open a PR to deduplicate the entries? I'd recommend explicitly listing the older platforms with pip entries, and anywhere they're availabe from binary packages with the wildcard notation to allow the rule to match expected future distributions including the binary packages again.

**Comment by tylernewnoise** [comment]
Hi and a happy new year.

Thx for pointing it out - I'll make the PR asap.
