### ISSUE TITLE
ROS melodic requires downgrading packages in order to install

### ISSUE THREAD

**Issue by zzh112119** [ros/rosdistro#23360]
Hi,

I updated my machine from Ubuntu 16 to Ubuntu 18 a couple of days ago. First I tried using apt-get to install:
```
sudo apt-get -y install 'ros-melodic-desktop'
```

And I faced the following error when trying to install ros-melodic-desktop through apt-get install:

```
STDERR:

E: Unable to correct problems, you have held broken packages.



MSG:

'/usr/bin/apt-get -y install 'ros-melodic-desktop'' failed: E: Unable to correct problems, you have held broken packages.`
```

It seemed to be a dependency issue that would not be solved with apt-get. So I tried to install it through aptitude:

```
sudo aptitude install ros-melodic-desktop
```
This time aptitude shows me that the detailed dependency issue. 
```
The following packages have unmet dependencies:
 python2.7-dev : Depends: python2.7 (= 2.7.15-4ubuntu4~18.04.2) but 2.7.17-1~18.04 is installed
                 Depends: libpython2.7 (= 2.7.15-4ubuntu4~18.04.2) but 2.7.17-1~18.04 is installed
 libjpeg-turbo8-dev : Depends: libjpeg-turbo8 (= 1.5.2-0ubuntu5.18.04.1) but 1.5.2-0ubuntu5.18.04.3 is installed
 libpython3.6-dev : Depends: libpython3.6-stdlib (= 3.6.8-1~18.04.3) but 3.6.9-1~18.04 is installed
                    Depends: libpython3.6 (= 3.6.8-1~18.04.3) but 3.6.9-1~18.04 is installed
 libsqlite3-dev : Depends: libsqlite3-0 (= 3.22.0-1ubuntu0.1) but 3.22.0-1ubuntu0.2 is installed
 libpython2.7-dev : Depends: libpython2.7-stdlib (= 2.7.15-4ubuntu4~18.04.2) but 2.7.17-1~18.04 is installed
                    Depends: libpython2.7 (= 2.7.15-4ubuntu4~18.04.2) but 2.7.17-1~18.04 is installed
 libcurl4-openssl-dev : Conflicts: libssl1.0-dev but 1.0.2n-1ubuntu5.3 is installed
 libssl-dev : Depends: libssl1.1 (= 1.1.1-1ubuntu2.1~18.04.4) but 1.1.1-1ubuntu2.1~18.04.5 is installed
              Conflicts: libssl1.0-dev but 1.0.2n-1ubuntu5.3 is installed
 libssl1.0-dev : Conflicts: libssl-dev but 1.1.1-1ubuntu2.1~18.04.4 is to be installed
 python3.6-dev : Depends: python3.6 (= 3.6.8-1~18.04.3) but 3.6.9-1~18.04 is installed
                 Depends: libpython3.6 (= 3.6.8-1~18.04.3) but 3.6.9-1~18.04 is installed
open: 39; closed: 2887; defer: 2; conflict: 3  
```

I was able to install ros by downgrading packages/resolving conflicts. But I'd like to know what's going on here and what can be done to resolve the issues more elegantly since I'm about to upgrade another machine.

**Comment by tfoote** [comment]
Looking at some of your version numbers you appear to have enabled bionic-updates( I see libpython2-7-dev a 2.7.17-1~18.04  https://packages.ubuntu.com/bionic-updates/libpython2.7-dev replacing the standard https://packages.ubuntu.com/bionic/libpython2.7-dev

You appear to have libssl1.0 installed https://packages.ubuntu.com/bionic/libssl1.0-dev which is conflicting with libssl1.1 which is now the default version. 


Looking at ROS we don't call out a specific version and take the system version of libssl-dev 
https://github.com/ros/rosdistro/blob/4a9d076958baea5570e999054b772999cf7b2909/rosdep/base.yaml#L3331-L3340

So I would suggest that you look at your upgrade process and see why it pulled in the older libssl1.0 and see if you can upgrade that or all those packages to use the newer default libssl. https://packages.ubuntu.com/bionic/libssl-dev

This doesn't appear to be a ROS problem, but a general xenial to bionic upgrade problem. Please look for answers and ask follow up questions on the Ubuntu forums.
