### ISSUE TITLE
Questions on updating bloom tracks.yaml

### ISSUE THREAD

**Issue by ErwanCL** [ros/rosdistro#23415]
Hello,

I am working on a ROS driver, on which the organization has been updated some times ago (#20874).
Today, a new version has been updated, and released using all the bloom-release system (#23412 , #23413 ).
Everything worked fine, but I realized that the upstream repository defined in the `tracks.yaml` file hasn't been changed, a little oversight from me, as it is my first package release.

I just want to ask questions, in order to be sure to avoid errors.
According to the official page [http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease#bloom.2BAC8-Tutorials.2BAC8-PrepareUpstream.Preparing_the_Upstream_Repository), I can use the `--track <ros_distro> <your_repository_name> --edit` option, and then update the corresponding item for the upstream repository (`Upstream Repository URI`).
Is that correct ?

Thanks in advance,

Erwan

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

But yes, you can just use the edit like that. Or manually change the tracks.yaml file before you make the release.
