### ISSUE TITLE
PIP only package naming?

### ISSUE THREAD

**Issue by MatthijsBurgh** [ros/rosdistro#23767]
Should PIP only packages be named `XXX-pip` or `python-XXX-pip`? Both variants are in the rosdistro, so it is unclear to me what the standard is.

**Comment by tfoote** [comment]
I would suggest that we standardize to use `python-XXX-pip`. This will make it much clearer when a similar debian rule appears side by side for sorting. 

To that end it should probably be `python3-XXX-pip` since all new platforms will be on python3 now.

**Comment by MatthijsBurgh** [comment]
Fixed by #23836
