### ISSUE TITLE
MacOS install with (deprecated) Python2.7

### ISSUE THREAD

**Issue by iPsych** [ros/rosdistro#23889]
There are some optimized ROS install script for MacOS Catalina, (like https://gist.github.com/ahoarau/dd521343494d9ec3ffb25da3f61f346d). 
However, I face below error repeatedly, and the problem seems to be caused by Python 2.7 deprecated issue (python@2 cannot be installed through homebrew).

> [build] Summary: 25 of 207 packages succeeded.                                 
> [build]   Ignored:   30 packages were skipped or are blacklisted.              
> [build]   Warnings:  3 packages succeeded with warnings.                       
> [build]   Abandoned: 181 packages were abandoned.                              
> [build]   Failed:    1 packages failed.                                        
> [build] Runtime: 57.3 seconds total.                                           
> [build] Note: Workspace packages have changed, please re-source setup files to use them.
>

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments. Make sure to provide enough information in your question to reproduce your problem. As well as include the actual errors that your encountering, not just the summary of the result.
