### ISSUE TITLE
stretch set to install gazebo9 in base.yaml

### ISSUE THREAD

**Issue by courtneyconroy** [ros/rosdistro#23942]
Hi,

I thought stretch could only install gazebo 7. In https://github.com/ros/rosdistro/blob/3fdab7657c8e10c29edb9c34538b09b118f5593a/rosdep/base.yaml, it is setting it to gazebo9. When trying to install ROS kinetic, it wont allow gazebo9 to install and therefore causing errors. Is there a way of changing it back to gazebo7? 

I'm using raspbian Stretch on raspberry pi 3b+

**Comment by tfoote** [comment]
If you ask for gazebo7 you can get gazebo7 we changed the default to be gazebo9. More info on the change is here: https://github.com/ros/rosdistro/pull/19843

You can always setup your own rosdep rules to override our defaults if you need something different for your platform.
