### ISSUE TITLE
General Fedora 31 Error

### ISSUE THREAD

**Issue by TorosluAdam** [ros/rosdistro#24222]
Hi there

I am taking multiple errors when trying to install ROS over source. as mentioned [ in this link](http://wiki.ros.org/melodic/Installation/Source) while i am resolving dependencies it shows me 

> 

> ERROR:` Rosdep experienced an error: rosdep OS definition for [python-opencv:fedora] must be a dictionary, string, or list: None
> 
> > Please go to the rosdep page [1] and file a bug report with the stack trace below.
> 
> > [1] : http://www.ros.org/wiki/rosdep
> 
> rosdep version: 0.18.0
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/rosdep2/main.py", line 144, in rosdep_main
>     exit_code = _rosdep_main(args)
>   File "/usr/local/lib/python3.7/site-packages/rosdep2/main.py", line 428, in _rosdep_main
>     return _package_args_handler(command, parser, options, args)
>   File "/usr/local/lib/python3.7/site-packages/rosdep2/main.py", line 537, in _package_args_handler
>     return command_handlers[command](lookup, packages, options)
>   File "/usr/local/lib/python3.7/site-packages/rosdep2/main.py", line 737, in command_install
>     uninstalled, errors = installer.get_uninstalled(packages, implicit=options.recursive, verbose=options.verbose)
>   File "/usr/local/lib/python3.7/site-packages/rosdep2/installers.py", line 445, in get_uninstalled
>     resolutions, errors = self.lookup.resolve_all(resources, installer_context, implicit=implicit)
>   File "/usr/local/lib/python3.7/site-packages/rosdep2/lookup.py", line 401, in resolve_all
>     self.resolve(rosdep_key, resource_name, installer_context)
>   File "/usr/local/lib/python3.7/site-packages/rosdep2/lookup.py", line 485, in resolve
>     installer_key, rosdep_args_dict = definition.get_rule_for_platform(os_name, os_version, installer_keys, default_key)
>   File "/usr/local/lib/python3.7/site-packages/rosdep2/lookup.py", line 148, in get_rule_for_platform
>     raise InvalidData('rosdep OS definition for [%s:%s] must be a dictionary, string, or list: %s' % (self.rosdep_key, os_name, data), origin=self.origin)
> rosdep2.core.InvalidData: rosdep OS definition for [python-opencv:fedora] must be a dictionary, string, or list: None
> 

i looked for every open/closed issues in here and found some solutions. i found out that python.yaml file shown as "null" on python-opencv fedora. when i add --0s=fedora:29 to the terminal code this time shows me gazebo-dev, gazebo9 and libgazebo9 errors. When i also looked at base.yaml file most of these files shown as "30" fedora. 

also some of the operands has different names, like opencv-python. i think it should be python-opencv.

Could you guys please help me about these problems? I really want to use ROS on my project.on the other hand i dont want to change my os to ubuntu. Thanks for your help. @tfoote

**Comment by tfoote** [comment]
The fedora rule for python-opencv is explicitly null for anything but fedora 29. You will need to lookup if there's another resolution for Fedora 30 or 31. But there's likely a reason that it's explicitly set to null. You'll probably want to look at the git history for it. If there's an equivalent please open a pull request with an update to the rosdep rule. There's a guide for contributing rules here: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md
