### ISSUE TITLE
Dashing Package Sync

### ISSUE THREAD

**Issue by JWhitleyWork** [ros/rosdistro#24765]
Is there currently an ETA on the next package sync for ROS Dashing? The last one was on 3/17 and there are some big package changes waiting like a new version of CycloneDDS.

**Comment by tfoote** [comment]
There's the discussion at https://discourse.ros.org/t/preparing-for-dashing-sync-and-patch-release-2020-03-17/13087/8 closing this ticket to avoid parallel threads.
