### ISSUE TITLE
URL for ezrassor_controller_server 404 error

### ISSUE THREAD

**Issue by zmichaels11** [ros/rosdistro#26144]
The URL referred by `ezrassor_controller_server` results in a 404 error.
URL: https://github.com/EZRASSOR/ezrassor_controller_server-release.git
https://github.com/ros/rosdistro/blob/d5d00b1394346761df921c3be0128d32327714bc/melodic/distribution.yaml#L2607

**Comment by dirk-thomas** [comment]
This was removed in #26175.
