### ISSUE TITLE
Foxy release tag for 2020-09-10 sync?

### ISSUE THREAD

**Issue by seanyen** [ros/rosdistro#26546]
https://discourse.ros.org/t/new-packages-for-foxy-fitzroy-2020-09-10/16348/2

It would be great that we will have the release tag for the sync. Thanks!

cc @jacobperron

**Comment by jacobperron** [comment]
Thanks for the ping, I've created a [tag](https://github.com/ros/rosdistro/tree/foxy/2020-09-10) the latest sync.
