### ISSUE TITLE
rosdep No definition of [rcpputils] on ArchLinux

### ISSUE THREAD

**Issue by RTrioux** [ros/rosdistro#27744]
Hi,

I'm trying to setup micro-ros on ArchLinux/zsh/ROS2 Foxy environment.
At some point the setup script run a rosdep install command

=== ./freertos_apps (git) ===
Clonage dans '.'...
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
rclc_lifecycle: No definition of [osrf_testing_tools_cpp] for OS [arch]
libyaml_vendor: No definition of [rcpputils] for OS [arch]
ros2trace: No definition of [ros2cli] for OS [arch]
rosidl_typesupport_cpp: No definition of [rcpputils] for OS [arch]
tracetools_launch: No definition of [launch_ros] for OS [arch]
rosidl_default_runtime: No definition of [rosidl_typesupport_introspection_cpp] for OS [arch]
rcutils: No definition of [osrf_testing_tools_cpp] for OS [arch]
rcl_action: No definition of [osrf_testing_tools_cpp] for OS [arch]
rcl_lifecycle: No definition of [osrf_testing_tools_cpp] for OS [arch]
tracetools_test: No definition of [launch_ros] for OS [arch]
rcl_logging_noop: No definition of [launch_testing] for OS [arch]
rmw: No definition of [osrf_testing_tools_cpp] for OS [arch]
rosidl_typesupport_c: No definition of [mimick_vendor] for OS [arch]
rcl: No definition of [rcpputils] for OS [arch]
rosidl_default_generators: No definition of [rosidl_typesupport_introspection_cpp] for OS [arch]
rclc: No definition of [osrf_testing_tools_cpp] for OS [arch]
rmw_implementation: No definition of [rcpputils] for OS [arch]
test_rmw_implementation: No definition of [rmw_dds_common] for OS [arch]

All these missing packages are git repositories,
I checked on rosdistro/rosdep, all these keys are defined here but only under "ubuntu focal"
[rosdistro-foxy-distribution.yaml](https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml)

When I type:
`rosdep resolve rcpputils`

This is what I get.

ERROR: No definition of [rcpputils] for OS [arch]

No definition of [rcpputils] for OS [arch]
        rosdep key : rcpputils
        OS name    : arch
        OS version : 
        Data:
_is_ros: true
                osx:
                  homebrew:
                    packages:
                    - ros/foxy/rcpputils
                ubuntu:
                  focal:
                    apt:
                      packages:
                      - ros-foxy-rcpputils

Interesting thing, there is an osx entry as well, despite I found no file with rcpputils and osx/homebrew inside.
Also rcpputils is not even available on apt or homebrew according to their respective website.

The only other place I found something related to these package is the yaml that the script download from ros2 repo:
[foxy ros2.repo](https://github.com/ros2/ros2/blob/foxy/ros2.repos)

Do you have some explanation about what's going on or how can I solve this ?
I'm confused about all of this
Thanks for considering this issue.

**Comment by jacobperron** [comment]
All of the packages you listed that are unable to be resolved are "core" ROS 2 packages. To install these for Linux, we provide 
- [debs via a ROS 2 apt repository](https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Debians/)
- an [archive with pre-built binaries](https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Install-Binary/)
- or [build from source instructions](https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/)

Note, all of the above instructions assume you are using Ubuntu (20.04, for Foxy). ArchLinux is not an officially supported platform, which is probably why `rosdep` is not able to install packages from the distribution.yaml. I'm not sure if micro-ROS supports ArchLinux either, you'd have to check with that project.

I found a few community discussions that seem to indicate that building from source is probably the only option at the moment:

- https://discourse.ros.org/t/some-tips-for-ros2-on-archlinux/17768
- https://discourse.ros.org/t/get-ros2-working-on-archlinux/12827/14

Good luck!
