### ISSUE TITLE
Builds on ubuntu_focal_armhf are failling with a SSL/TLS error when fetching rosdistro index

### ISSUE THREAD

**Issue by hrnr** [ros/rosdistro#27939]
Hi,

two of my builds are failing on armhf ubuntu focal agents with the following error:

```
urllib.error.URLError: <urlopen error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)> (https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml)>
```

Jobs that are failing are:
* https://build.ros.org/job/Nbin_ufhf_uFhf__explore_lite__ubuntu_focal_armhf__binary/
* https://build.ros.org/job/Nbin_ufhf_uFhf__multirobot_map_merge__ubuntu_focal_armhf__binary/

It is failing quite consistently and does not look like a network issue. It is very interesting that the other jobs (eg. my dependecies) are not suffering.

Could somebody help me investigate please?

Cheers,
Jiri

**Comment by mikeferguson** [comment]
A few others have reported this on discourse.ros.org: https://discourse.ros.org/t/ssl-failure-in-buildfarm-jobs-ros1/18304

**Comment by hrnr** [comment]
thanks for the pointer. The problem has been solved in ros infra.
