### ISSUE TITLE
"Failed to open pull request" with HTTP Error 404

### ISSUE THREAD

**Issue by ROBOTIS-Will** [ros/rosdistro#29168]
Hi, 

After enabling GitHub 2FA for my account, and applying [manually authorizing bloom to generate PR](http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization), my PR to rosdistro starts failing with 404 error.
```
Failed to open pull request: GithubException - HTTP Error 404: Not Found (https://api.github.com/repos/ros/rosdistro/pulls): None
```
![image](https://user-images.githubusercontent.com/26239359/114819347-51843080-9df8-11eb-95d0-858e15da6808.png)

Is this something have to do with the 2FA?

**Comment by ROBOTIS-Will** [comment]
I found an identical issue on ros-infrastructure/bloom
https://github.com/ros-infrastructure/bloom/issues/632
Closing this. Thanks!

**Comment by Kukanani** [comment]
Just wanted to follow up on this and note that I don't have 2FA on my account, so I doubt that is the source of the issue.
