### ISSUE TITLE
rclc: bloom release galactic: 'origin/galactic^{commit}': unknown revision

### ISSUE THREAD

**Issue by JanStaschulat** [ros/rosdistro#29738]
Hi, I have a question regarding executing the bloom release for Galactic. I created the branch [galactic](https://github.com/ros2/rclc/tree/galactic) on `rclc` repository and updated the bloom release configuration. Since then, the bloom release fails for Galactic. 

For example:  The build job in this pull request https://github.com/ros2/rclc/pull/94 fails, because the revision `origin/galactic^{commit}` was not found, i.e. the branch `galactic`was not found:

```
22:37:00  > git rev-parse refs/remotes/origin/pr/94/merge^{commit} # timeout=10
22:37:00 Merging Revision 44e0f6d2cfb7135aae7de2fd01112a11dc8849ff (refs/remotes/origin/pr/94/merge) to origin/galactic, UserMergeOptions{mergeRemote='origin', mergeTarget='galactic', mergeStrategy='DEFAULT', fastForwardMode='FF'}
22:37:00  > git rev-parse origin/galactic^{commit} # timeout=10
22:37:00 FATAL: Command "git rev-parse origin/galactic^{commit}" returned status code 128:
22:37:00 stdout: origin/galactic^{commit}
22:37:00 
22:37:00 stderr: fatal: ambiguous argument 'origin/galactic^{commit}': unknown revision or path not in the working tree.
22:37:00 Use '--' to separate paths from revisions, like this:
22:37:00 'git <command> [<revision>...] -- [<file>...]'
```
[Complete console output of build-job#50](https://build.ros2.org/job/Gpr__rclc__ubuntu_focal_amd64/50/console)

The [last successful run of the galactic build job](https://build.ros2.org/job/Gpr__rclc__ubuntu_focal_amd64/lastStableBuild/consoleFull) used the `master` branch:
```
06:07:37  > git rev-parse origin/master^{commit} # timeout=10
06:07:37  > git config core.sparsecheckout # timeout=10
06:07:37  > git checkout -f origin/master # timeout=10
```

I updated the branch from `master` to `galactic` in this [PR #29683](https://github.com/ros/rosdistro/pull/29683) manually.
Then, I updated the branch name with the bloom-release tool also in this [PR #29702](https://github.com/ros/rosdistro/pull/29702) with the command line:

`bloom-release --rosdistro galactic --edit-track --track galactic rclc`, 

During configuration, I changed the `Upstream Devel Branch` to `galactic`: 
```
Version:
  :{ask}
    This means that the user will be prompted for the version each release.
    This also means that the upstream devel will be ignored.
  :{auto}
    This means the version will be guessed from the devel branch.
    This means that the devel branch must be set, the devel branch must exist,
    and there must be a valid package.xml in the upstream devel branch.
  <version>
    This will be the version used.
    It must be updated for each new upstream version.
  [':{auto}']:
Upstream Devel Branch:
  <vcs reference>
    Branch in upstream repository on which to search for the version.
    This is used only when version is set to ':{auto}'.
  ['master']: galactic 
```

We are already using `ros-tooling/setup-ros@0.2.1` (new GPG key) and `ros-tooling/action-ros-ci@0.2.1`.

On my local Linux machine, I tested the `git rev-parse origin/galactic^{commit}` command on a freshly cloned repo:
```
~/temp$ git clone https://github.com/ros2/rclc.git
~/temp$ cd rclc
~/temp/rclc$ git rev-parse origin/galactic^{commit}
2cf334c9d0c15e5871227e49c193e413c0b058e3
```
which seems to work, i.e. the branch `galactic` exists. The value is the [most recent commit hash](https://github.com/ros2/rclc/commit/2cf334c9d0c15e5871227e49c193e413c0b058e3) of the `galactic` branch.

What is the reason for this error message? How can I resolve it?

**Comment by JanStaschulat** [comment]
Any feedback?

**Comment by nuclearsandwich** [comment]
@JanStaschulat I don't see how the PR job failures are related to the bloom release?

Based on your reported bloom release operations you have done everything as I would have done it and the _release_ builds for rclc on Galactic are currently succeeding on both [amd64](https://build.ros2.org/job/Gbin_uF64__rclc__ubuntu_focal_amd64__binary/) and [armv8](https://build.ros2.org/job/Gbin_ufv8_uFv8__rclc__ubuntu_focal_arm64__binary/).

It does look like PR jobs have recently started failing for rclc and upon investigation it looks like it was a problem with the specific Jenkins agent that the jobs were being run on. By temporarily disabling that agent I was able to re-trigger an example PR's CI: https://github.com/ros2/rclc/pull/100#issuecomment-857985148

That build has succeeded and I'll be retiring the Jenkins agent which was exhibiting the problem.

**Comment by JanStaschulat** [comment]
@nuclearsandwich Thanks for re-triggering the ci-job. The build is now successful. I created a dummy new PR https://github.com/ros2/rclc/pull/101 which also runs successfully at the build farm. Thanks a lot. 

I wonder, if this problem occurs again in the future, could I re-start the build job also? Or should I report this problem here at rosdistro again? I am asking this question, because just creating a new pull request to galactic (with trivial change) did not resolve the error.

**Comment by nuclearsandwich** [comment]
> However, what would I do, if this problem occured again?

We recently set up a repository specifically for fielding issue reports with Open Robotics infrastructure at [osrf/infrastructure](https://github.com/osrf/infrastructre) and I think that reporting problems like this there is reasonably valid. An issue there would help us track and mitigate the immediate issue and can reference any long running issues with our ros_buildfarm or cookbook deployment logic for trying to reduce the incidence of similar problems over time. The issue template in that repository will also recommend checking [ROS Answers](https://answers.ros.org) for similar problems before opening an issue in case there is a self-service solution and that should still be done as a first step, however there was not a self-service solution in this case. Thanks for raising the issue and hopefully by providing a directed place for these issues we'll be able to identify and respond more promptly.

**Comment by JanStaschulat** [comment]
@nuclearsandwich Great to have a dedicated repository to issue such error reports. 

You might want to correct the link to `osrf/infrastructure` in our post. It  has a typo: `https://github.com/osrf/infrastructre`

**Comment by nuclearsandwich** [comment]
> You might want to correct the link in our post. It has a typo: `https://github.com/osrf/infrastructre`

Thanks, I could have sworn I checked each link but that's how it goes I guess.
