### ISSUE TITLE
CI failure: "fatal: remotes/origin/master...HEAD: no merge base"

### ISSUE THREAD

**Issue by jacobperron** [ros/rosdistro#29964]
I've seen CI fail on multiple rosdistro PRs with:

```
fatal: remotes/origin/master...HEAD: no merge base
```

Example CI failures:

- https://github.com/ros/rosdistro/pull/29796/checks?check_run_id=2854228224
- https://github.com/ros/rosdistro/pull/29795/checks?check_run_id=2854225101

It seems like merging `master` with the PR branch resolves the issue.

**Comment by nuclearsandwich** [comment]
@cottsay it looks like https://github.com/ros/rosdistro/pull/29989 is failing even though it is up-to-date with master. I'm going to merge it because it's otherwise okay but 9a028e0 is the commit ID for a repro branch.
