### ISSUE TITLE
Question about adding a repo for python-gdal

### ISSUE THREAD

**Issue by rolker** [ros/rosdistro#30210]
I'm writing a node for Noetic on Ubuntu 20.04 (focal) that depends on python3-gdal.

Looking at rosdep/python.yaml to see how I should specify the dependency in my package.xml file, I found the python-gdal entry with various repos for what looks like python 2 versions of the package without a repo specified for ubuntu/focal.

My question is, do I add python3-gdal for focal under the existing python-gdal entry or do I create a new python3-gdal entry?

I suspect that adding to the existing entry would be OK, but I want to make sure before I craft a pull request.

**Comment by sloretz** [comment]
Please create a new entry for `python3-gdal`. I replied in #30211, but I also thought you might be interested in more context about Python 3 rosdep keys in REP 151: https://www.ros.org/reps/rep-0151.html#rosdep-keys . I'll close this for now and continue the discussion in #30211
