### ISSUE TITLE
[question] pytorch debian architecture specific

### ISSUE THREAD

**Issue by flynneva** [ros/rosdistro#30535]
So I've recently contributed some updates to the [`yolov3_pytorch_ros` package](https://github.com/vvasilo/yolov3_pytorch_ros) and would like to try and publish a release for it.

when I tried to `bloom-release` it, bloom gave me some warnings saying that some required dependencies (specifically `python-pytorch-pip`) were found but could not be used by the debian geneartor since they use the installer `pip`.

after doing some digging it looks like there is available a [debian release for `pytorch`](https://packages.debian.org/experimental/python3-torch), however it is only available for `amd64` and `armhf` architectures.

is there a way to safely add this as a rosdep key, im assuming to the `rosdep/base.yaml` file?

thanks in advanced for any tips or advice!

**Comment by hidmic** [comment]
> is there a way to safely add this as a rosdep key, im assuming to the `rosdep/base.yaml` file?

To the best of my knowledge, no, there's not concept of architecture in `rosdep` tooling. I do see `python3-torch 1.7.1` released to Debian Bullseye for all architectures though.

Anyhow, even if you succeeded to build a debian for Debian, you'd probably run into trouble when building debians for Ubuntu or when build rpms for RHEL. 

Have you considered using [`catkin_virtualenv`](https://github.com/locusrobotics/catkin_virtualenv) like [`haros_catkin`](https://github.com/rosin-project/haros_catkin/tree/d04963766f76bb29be732f7cf91a53920bdc1d9b) does?
