### ISSUE TITLE
open3d-python deprecated?

### ISSUE THREAD

**Issue by mvoelk** [ros/rosdistro#30995]
When I install open3d for python via `rosdep` (`python3-open3d-pip`) I get version 0.3.0.0. When I install `open3d` via `pip3` I get version 0.13.0.

Is this on purpose or can we fix this somehow?

**Comment by jacobperron** [comment]
The rosdep key actually points to [open3d-python](https://pypi.org/project/open3d-python/), not [open3d](https://pypi.org/project/open3d/). Both PyPi packages point to the same source code, so I guess open3d-python is no longer maintained/updated. We could probably update the [rosdep rule](https://github.com/ros/rosdistro/blob/b9ba9d4c7c4629b2e95f043897e29ff131051625/rosdep/python.yaml#L3043-L3052) to point to the "newer" PyPi package. Feel free to open a pull request.

**Comment by jacobperron** [comment]
It might also be worth opening an issue [upstream](https://github.com/isl-org/Open3D), reporting this discrepancy.

**Comment by hidmic** [comment]
@mvoelk are you willing to contribute another rosdep key?

**Comment by mvoelk** [comment]
@hidmic I thought it would be faster if one of you could replace 'open3d-python' with 'open3d' without a long discussion... I'm sorry I'm too lazy to fork the repo and make a pull request :)

**Comment by tfoote** [comment]
I'm going to close this and ask if people are running into this issue to propose a fix in a PR that we can review.
