### ISSUE TITLE
rosdistro entry requiring PPA? 

### ISSUE THREAD

**Issue by SteveMacenski** [ros/rosdistro#31215]
We're looking to add a new package to Nav2 that needs `xtensor` which has public releases for 18.04/21.10 but not 20.04. There is, however, a PPA with the package available to use (see below). Is it possible to get rosdistro entries requiring adding a new PPA? I do not believe I've seen documentation about this previously.  

https://answers.launchpad.net/ubuntu/+source/xtensor/+question/699443

**Comment by jacobperron** [comment]
I'm pretty sure ROS infrastructure doesn't support requiring a specific PPA for a rosdep rule.

@nuclearsandwich may have a more concrete answer.

**Comment by SteveMacenski** [comment]
I assumed so, but figured it would be good to ask :smile:

**Comment by mikeferguson** [comment]
I know in the past @tfoote helped me import a PPA-built version of ceres-solver into packages.ros.org when the built was broken in a particular Ubuntu distro.

**Comment by hidmic** [comment]
@nuclearsandwich shall we close? AFAIK there's no plan to support custom PPAs in the foreseeable future.

**Comment by tfoote** [comment]
Yes, we explicitly require that content is either in the upstream or the ROS sources: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#ubun

If it's already released into 18.04 and 21.10 we can probably assist getting it backported  20.04 with the debian/ubuntu maintainers if it's still of interest. Email me direcly and we can start a thread looking to get it released upstream into focal.

**Comment by nuclearsandwich** [comment]
Thanks @tfoote  for jumping in and apologies upthread for not fielding the mentions. I've been swamped and am in the process of clearing out direct mentions before declaring GitHub bankruptcy so that I'm in a better place going into 2022.

**Comment by SteveMacenski** [comment]
OK, will do when the time comes!
