### ISSUE TITLE
Galactic compiled for Debian

### ISSUE THREAD

**Issue by mmege** [ros/rosdistro#31460]
As mentioned [here](https://www.ros.org/reps/rep-2000.html#id41), Galactic packages should be available for Debian Bullseye.
I'm not sure if I missing something but It seems that [distribution.yml](https://github.com/ros/rosdistro/blob/master/galactic/distribution.yaml) is lacking the dependencies link for this distribution as well as the packages [here](http://packages.ros.org/ros2/ubuntu/dists/bullseye/).

**Comment by cottsay** [comment]
If you look at the targeted platforms table in [REP 2000](https://www.ros.org/reps/rep-2000.html#galactic-geochelone-may-2021-november-2022), it shows that Debian Bullseye is a Tier-3 supported platform for compilation from source only, as indicated by `[s]` in the table. If support for deb packages were declared, there would be a `[d]` in the Debian column.
