### ISSUE TITLE
[question] Which release repository for a new Noetic webots_ros release

### ISSUE THREAD

**Issue by BenjaminHug8** [ros/rosdistro#31536]
Hi, we want to make a new `webots_ros` release for `Noetic` but it seems we should do it from `ros-gbp/webots_ros-release` and not anymore from `https://github.com/cyberbotics/webots_ros-release`.

(Similar case we had for ROS 2 [here](https://github.com/ros/rosdistro/pull/31123#discussion_r743050092) )

If it is the case can you give us access to this release repository please?

Here is the list of members of the Webots maintainer group: @omichel, @BenjaminHug8, @stefaniapedrazzi, @BenjaminDeleze and @ad-daniel.

Regards,
Benjamin

**Comment by tfoote** [comment]
It's fine to keep using your cyberbotics release repository for ROS 1 releases. For ROS 2 we updated the policy as need them to be centralized so that we can do the rolling updates automatically.
