### ISSUE TITLE
serial not available for noetic

### ISSUE THREAD

**Issue by ardabbour** [ros/rosdistro#31855]
Tested on Pop_OS! 20.04 and the docker image osrf/ros:noetic-desktop-full

Despite being defined [here](https://github.com/ros/rosdistro/blob/master/noetic/distribution.yaml#L8707), it is not available. This only seems to affect noetic, and not melodic.

**Comment by jacobperron** [comment]
The package has been built, but not been synced to the main repository yet (http://repositories.ros.org/status_page/ros_noetic_default.html?q=serial). I expect it will become available on Noetic after the [next sync](https://discourse.ros.org/t/preparing-for-noetic-sync-2022-01-20/23873).
