### ISSUE TITLE
Package python-transitions not found on Ubuntu 20.04

### ISSUE THREAD

**Issue by invenibo** [ros/rosdistro#31918]
Running rosdep install on a package containing the dependency `python-transitions` on ubuntu 20.04 (or in a docker on ros:noetic) produces the following error: 

```
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y python-transitions] failed
  apt: Failed to detect successful installation of [python-transitions]
```
The definition in the python.yaml seems to use pip to install the package on older versions of ubuntu:
https://github.com/ros/rosdistro/blob/f1a2bc6aa7c3e7f7007808f2680ee77b4f92679c/rosdep/python.yaml#L5243-L5250

For ubuntu 20.04 there is an apt package available under the name `python3-transitions`. Otherwise it can also be installed using pip.

**Comment by tfoote** [comment]
It appears to only be on bionic and nothing newer that's currently available: https://packages.ubuntu.com/bionic/python-transitions  

Confirmed that it's available on all supported Ubuntu platforms for python3: https://packages.ubuntu.com/bionic/python3-transitions. And it's on debian starting with bullseye: https://packages.debian.org/bullseye/python3-transitions

If you'd like to use the python 3 version please consider creating a pull request to add it as a rule, finding the equivalent on the other platforms as well.  I've opened #32380 to delist it on all but bionic.
