### ISSUE TITLE
[pkg release] Libserial version on Jenkins

### ISSUE THREAD

**Issue by andreabu** [ros/rosdistro#32095]
Hi all,

I'm raising this issue because I'm struggling with the binary release of a ROS metapackage (`mia_hand_ros_pkgs`).

What is basically happening is that, when I build the package locally and during ROS pre-release tests, everything works fine. However, when it comes to build on Jenkins, I start receiving build failure notifications via e-mail. The reason for the failure is related to a third-party library, named [libserial](https://github.com/crayzeewulf/libserial), which I'm linking against my package source code. Briefly, compilation fails because libserial header files can not be found through `#include` directives.

After some unsuccessful fix trials, I noticed, through Jenkins log, that Jenkins is automatically installing a pre-release version of libserial (i.e., 0.6.0rc3). However, when installing libserial on my local machine (through `sudo apt install libserial-dev`), the version installed is 1.0.0. The same happens during ROS pre-release tests. Version 1.0.0 seems to be [much stabler](https://github.com/crayzeewulf/libserial/releases) than 0.6.0rc3. Moreover, it seems that some bugs related to [libserial linking](https://github.com/crayzeewulf/libserial/issues/113) have been fixed with version 1.0.0.

I think this might be the reason why the package is building correctly locally and during pre-release tests, but not on Jenkins. So, would it be possible to configure Jenkins to install the latest libserial version?

I don't know if this is the right place to raise this issue. If not, I would ask where I should raise it. Moreover, if you need additional information (e.g., detailed logs), I'm available.

Thanks in advance for the availability.

**Comment by tfoote** [comment]
The correct place for this sort of question is on https://answers.ros.org

In the future please make sure to link to specific builds with the specific failures. The detailed logs are all publicly available. After searching around for a while I was able to find the failing build https://build.ros.org/job/Nbin_db_dB64__mia_hand_driver__debian_buster_amd64__binary/87/console 

On Ubuntu Focal libserial-dev is at [1.0.0](https://packages.ubuntu.com/focal/libserial-dev) however the failing build is on Debian Buster at [0.6.0](https://packages.debian.org/buster/libserial-dev) If you ran a prerelease on Debian buster you should get the same failure. With multiple target platforms you need to make sure that your code works with all versions of the supporting libraries. You might need to do an `#ifdef` or some other logic to be compatible if there's large changes such as headers relocated.
