### ISSUE TITLE
why ros-galactic-realsense2-camera package has been removed?

### ISSUE THREAD

**Issue by Nir-Az** [ros/rosdistro#32467]
Hi,

Can someone please say why `ros-galactic-realsense2-camera` had been removed?
as mentioned [here](https://discourse.ros.org/t/new-packages-for-galactic-geochelone-2022-03-14/24688)
The last change is that it had been updated to version 4.0.2.

It could be that the tag and branch name didn't match. apparently bloom-release did not update the branch name to the new one.
I opened a new PR for version 4.0.3 and manually updated the branch name.

So my questions are:

1. Why did ros-galactic-realsense2-camera package was removed?
2. If someone knows why bloom-release do not update the PR with the new branch name?
Thanks

Thanks
Nir

**Comment by cottsay** [comment]
There was some discussion in the discourse thread and I believe these questions have been answered. If there's anything that's still unclear, let's continue the discussion there.

Thanks!
