### ISSUE TITLE
Please, consider adding libopenni2-dev for rhel:8 

### ISSUE THREAD

**Issue by jlblancoc** [ros/rosdistro#34332]
Hi, 

A package I maintain uses libopenni2 and bloom-release complains about: 

```
Failed to resolve libopenni2-dev on rhel:8 
```

But **I think** it exists: https://packages.fedoraproject.org/pkgs/libfreenect/libfreenect-openni/, right? 

I'm not familiar enough with `rhel` pkg names to make the PR myself...

**Comment by DLu** [comment]
I made https://github.com/ros/rosdistro/pull/34443 for you but I also am not very familiar with `rhel`
