### ISSUE TITLE
How to patch ROS2 release.

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros/rosdistro#34385]
I went through the patch process for third party release but the following command fails `git-bloom-release foxy`. Is there another process that should be used?

**Comment by Levi-Armstrong** [comment]
I was following the release process for a third party found [here](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty)

**Comment by Levi-Armstrong** [comment]
I am trying to release [this](https://github.com/tesseract-robotics-release/qt_advanced_docking_system-release) for foxy where I was able to create a patch for noetic but for some reason I was not able to for foxy.

**Comment by nuclearsandwich** [comment]
This type of issue is probably best served by [ROS Answers](https://answers.ros.org) at the moment.

> following command fails `git-bloom-release foxy`

Can you please share the output of the failed command, as well as the values you entered when prompted for the upstream version and tag? For example, I had no problem re-releasing 3.8.2 from a forked version of the release repository.

**Comment by nuclearsandwich** [comment]
@Levi-Armstrong any updates here?

**Comment by nuclearsandwich** [comment]
Closing due to lack of response. Please re-open this issue or open a new one if you're still having problems.
