### ISSUE TITLE
Add a requirements.txt for contributors

### ISSUE THREAD

**Issue by RFRIEDM-Trimble** [ros/rosdistro#35109]
As a contributor to this package, right now the way I install python requirements for contributing is copying each requirement [from the table in the contributing guidelines](https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#how-to-submit-pull-requests). Any thoughts on dumping the pip requirements into a file called `requirements.txt` and instructing contributors to install that? 

Requirements.txt files are a familiar way for python developers to install dependencies.
```
cd rosdistro
python3 -m pip install -r requirements.txt
```

-Ryan

**Comment by mjcarroll** [comment]
@RFRIEDM-Trimble This would be a helpful addition.  If you have a chance to contribute, I would be happy to review.

**Comment by Ryanf55** [comment]
Yes, I can do this. Please assign it to me.

**Comment by Ryanf55** [comment]
Since `python-nose` apt package does not exist in Ubuntu Jammy, it's now `python3-nose`, are you ok with using `pip` for everything I can?

**Comment by Ryanf55** [comment]
This can be closed.
