### ISSUE TITLE
PR testing not working

### ISSUE THREAD

**Issue by saching13** [ros/rosdistro#36083]
I recently changed the version branches of the releases in the rosdistro and the tracks. 
But PR testing is still not working. 
Dummy PR to cross check that is [here](https://github.com/luxonis/depthai-ros/pull/222)
Any suggestions on what I might be missing here ?

**Comment by tfoote** [comment]
I think that you were using the wrong verbiage I retried with `@ros-pull-request-builder retest this please` and it triggered.  As documented here: http://wiki.ros.org/buildfarm/Pull%20request%20testing

![image](https://user-images.githubusercontent.com/447804/218396069-f0101f9b-66df-4abf-ab3b-afd65a3272d9.png)


The other two triggers weren't hit as the PR was already existing before the job reconfigured at 11pm on the 6th. As well the commits were at 9pm on the 6th.
