### ISSUE TITLE
Conflicting numpy-quaternion and scipy versions

### ISSUE THREAD

**Issue by imontesino** [ros/rosdistro#36253]
## System
- OS: Ubuntu Focal 20.04
- ROS: ROS2 Foxy 

## Issue

Conflicting versions of `numpy-quaternion` and `scipy` via `rosdep`

Getting the following error at runtime:
```
File "/usr/local/lib/python3.8/dist-packages/quaternion/__init__.py", line 356, in from_rotation_matrix
     eigvals, eigvecs = linalg.eigh(K3.T, subset_by_index=(3, 3))
 TypeError: eigh() got an unexpected keyword argument 'subset_by_index'
```

Seem to be coming from this [latest commit](https://github.com/moble/quaternion/commit/b23734f349282d1097ececf5c612b2a45917cdd4) in `numpy-quaternion`. Since it is installed via pip it defaults to the latest version.
While the [installed scipy](https://packages.ubuntu.com/focal/python3-scipy) is via apt and is version 1.3.3 for Ubuntu 20.04 Focal

Is there any way of specifying the `numpy-quaternion` version in the python.yaml?

https://github.com/ros/rosdistro/blob/6d910cc1d5d760c0cbc27cebc471c12a72811fd6/rosdep/python.yaml#L3098-L3110

**Comment by clalancette** [comment]
No response in many months, so closing this out.
