### ISSUE TITLE
Add BigTree to rosdistro?

### ISSUE THREAD

**Issue by ipa-hsd** [ros/rosdistro#36424]
Currently for tree traversal, only `anytree` is listed in `rosdistro`: https://github.com/ros/rosdistro/blob/90d0bca39afdad90a70f04a1655b565a60bed7cd/rosdep/python.yaml#L6026 
I find it a bit limited and am interested in using [bigtree](https://github.com/kayjan/bigtree). Would this be possible or the maintainers need to agree to this? Sorry for my lack of knowledge about this.

**Comment by mjcarroll** [comment]
If you would like to add a key to rosdep, please follow the contributing guide for rosdep keys here: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions
