### ISSUE TITLE
`attrs` completely missing for Ubuntu Jammy

### ISSUE THREAD

**Issue by Interpause** [ros/rosdistro#37310]
After https://github.com/ros/rosdistro/commit/b88e07b7a3206ab31d6420d5f47c7fecef6e6c7e, `attrs` cannot be installed for Ubuntu Jammy anymore using either `python-attrs` or `python-attrs-pip`.

**Comment by nuclearsandwich** [comment]
Both of those rosdep keys implicitly refer to python2 libraries, which are not available or supported on Ubuntu Jammy. 

There is a python3-attr package in Ubuntu Jammy: https://packages.ubuntu.com/jammy/python3-attr which could be added to rosdep under a new key: `python3-attr` for use with distributions supporting Python 3 (all ROS 2 distributions and ROS Noetic).

**Comment by clalancette** [comment]
Since I don't think there is any further work to be done here, I'm going to close this out.  Feel free to reopen if I'm mistaken.
