### ISSUE TITLE
Add roboticstoolbox-python to the rosdep index

### ISSUE THREAD

**Issue by BrunoB81HK** [ros/rosdistro#39175]
The `roboticstoolbox-python` package is pretty useful, especially in scripts. I'm not sure if it's already possible, but I've not been able to install it through `rosdep`. Is it possible to add it to `rosdistro`? I would do a pull-request, but I'm not sure how `rosdistro` works.

Here are some (probably) useful links:
- [GitHub Repo](https://github.com/petercorke/robotics-toolbox-python)
- [PyPI](https://pypi.org/project/roboticstoolbox-python/)

Thanks a lot!

**Comment by clalancette** [comment]
Please feel free to open a pull request, following the guidelines in https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#rosdep-rules-contributions .  Please make sure to fill out the pull request template completely.

I'm going to close this one out.

**Comment by BrunoB81HK** [comment]
Thanks a lot for the tip. I'll try and submit a pull-request ASAP.
