### ISSUE TITLE
Old python3-mypy version on Ubuntu

### ISSUE THREAD

**Issue by Wojcik98** [ros/rosdistro#39208]
`python3-mypy` on Ubuntu is configured to be installed using system package [python3-mypy](https://packages.ubuntu.com/jammy/python3-mypy) which contains `mypy` in version `0.942`. That version has a bug that appears when using python version `>=3.10.7` (https://github.com/python/mypy/issues/13627), it was fixed in version `0.981`. Ubuntu's current python's version is `3.10.12`.

This prevents me from using `ament_mypy` in packages as mypy crashes.

`mypy` on pip is in the latest version `1.7.1`.

Should the rules here in `rosdistro` be changed to use `pip` installer for ubuntu, or should this be on mypy/ubuntu maintainers to release new version for ubuntu?

**Comment by nuclearsandwich** [comment]
> Should the rules here in rosdistro be changed to use pip installer for ubuntu, or should this be on mypy/ubuntu maintainers to release new version for ubuntu?

Version stability is part of the necessary trade-off for long term support distributions. See this comment https://github.com/ros/rosdistro/pull/39226#issuecomment-1858402401 for why pip cannot provide this dependency.
