### ISSUE TITLE
rosdep update: No such file or directory: '/usr/share/python3-rosdep2/debian.yaml'

### ISSUE THREAD

**Issue by mattxcnm** [ros/rosdistro#39489]
Attempting to run bash command: `rosdep update`, getting error: `ERROR: unable to process source [file:///usr/share/python3-rosdep2/debian.yaml]:
        <urlopen error [Errno 2] No such file or directory: '/usr/share/python3-rosdep2/debian.yaml'> (file:///usr/share/python3-rosdep2/debian.yaml)`

Tried `sudo rm /etc/ros/rosdep/sources.list.d/20-default.list`, then removing and reinstalling python3-rosdep (`sudo apt`). Still the same error.

System information:
Raspberry Pi 4b, arm64, Ubunutu Server 22.04
ROS2 Humble

**Comment by tfoote** [comment]
You look to have a combination of upstream and ROS packages, see https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Developer-Guide.html?highlight=streams#upstream-packages for more info. 

I'm going to close this. In the future or if you need more help on this, please ask questions on https://robotics.stackexchange.com/ according to our support policy:  We try to keep the issue tracker reserved for bugs and feature developments. If you do ask, please try to provide more context as to what you've installed and how specifically.
