### ISSUE TITLE
Remove locator_ros_bridge from iron and rolling

### ISSUE THREAD

**Issue by syyuen** [ros/rosdistro#39633]
I'd like to request the removal of the package locator_ros_bridge from the distro
- iron
- rolling
since the development is focusing on noetic and humble.

**Comment by mjcarroll** [comment]
You should be able to open a pull request removing the relevant sections from the iron and rolling distro files.

**Comment by syyuen** [comment]
Thanks, pull request is merged for rolling https://github.com/ros/rosdistro/pull/39677
