### ISSUE TITLE
PR #40033 causes packages to fail on build farm

### ISSUE THREAD

**Issue by rhaschke** [ros/rosdistro#40114]
PR #40033 increased the release number of several packages w/o committing corresponding releases, which causes those packages to fail on the build farm.
For example, for xacro the release version changed from `2.0.10-1` to `2.0.10-2`.
However, the release tag `debian/ros-rolling-xacro_2.0.10-2_jammy` doesn't exist, causing a CI failure when cloning the repo: https://build.ros2.org/job/Rsrc_uJ__xacro__ubuntu_jammy__source/11/display/redirect

**Comment by clalancette** [comment]
I think we are all set with this, as we are now fully transitioned to Noble.  So closing this out.  Feel free to reopen if I am mistaken.
