### ISSUE TITLE
 installation script missing for Humble

### ISSUE THREAD

**Issue by amar-jay** [ros/rosdistro#41139]
After installing ROS2 humble distro, though perfectly installed, it did not come with setup scripts.
I already have ROS2 iron on my pl and it works pretty fine. And no, this isn't my first time installing it

**Comment by mjcarroll** [comment]
This is not the correct location for this question.  Can you please try asking on https://robotics.stackexchange.com/ with more information about the way you are installing and what steps you have tried?
