### ISSUE TITLE
libgrpc key has mixed dev/binary packages

### ISSUE THREAD

**Issue by frankkusters** [ros/rosdistro#41602]
When submitting a pull request for adding `libflatbuffers`, I [received a suggestion](https://github.com/ros/rosdistro/pull/41519#pullrequestreview-2111290109) to consistently use the dev/devel packages, and to name the key after the Ubuntu package name.

My pull request was based on the `libgrpc` key, which then has the same issues. For example, in `fedora` the package should not be `grpc-cpp`, but `grpc-devel` (which includes the headers for C++). And the key itself should be renamed from `libgrpc` to `libgrpc-dev`.

I'm willing to submit a pull request to fix this, but changing this outright will cause issues with existing users of the key. What is the approach here?

**Comment by clalancette** [comment]
> I'm willing to submit a pull request to fix this, but changing this outright will cause issues with existing users of the key. What is the approach here?

There are 2 different issues with the `libgrpc` key:
1.  The name is incorrect; it really should be `libgrpc++-dev`.
2.  The keys are wrong for some distributions, like `fedora`, where it should point to the `-devel` package.

You are correct that we can't fix the first issue, as it would break existing packages.  So I'd say let's just leave that alone.  However, we can update the keys for the various distributions, as typically the `-dev` or `-devel` package also pulls in the regular package.  So I'd say submit a PR just updating the `fedora`, `rhel`, and maybe `alpine` packages, and that should be good enough.
