### ISSUE TITLE
DepthAI ROS packages missing in latest Noetic release

### ISSUE THREAD

**Issue by Serafadam** [ros/rosdistro#41775]
Hi, even though depthai-ros packages seem to be present in [new release](https://discourse.ros.org/t/new-packages-for-noetic-2024-06-20/38278), they are not available on current APT.

**Comment by mjcarroll** [comment]
There was a regression that was addressed (https://github.com/luxonis/depthai-ros/issues/540).  They should be back with the latest sync.

You can check packaging status here: https://repositories.ros.org/status_page/ros_noetic_default.html?q=depthai
