### ISSUE TITLE
Develop an ABI policy, notation and testing ability

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#418]
We have discussed abi versioning in packages.  

We should also have a way to test for ABI changes.  

There's been a bunch of discussions on the buildsystem sig: https://groups.google.com/forum/?fromgroups#!searchin/ros-sig-buildsystem/abi$20version
- how strict we are going to be
- how to flag abi incompatibility
- allow debbuild infrastructure to avoid rebuilding everything
- more stable jenkins with lots of jobs -- possibly look at upgrading or paying for a fix for the log size

**Comment by dirk-thomas** [comment]
Closing due to age and inactivity.
