### ISSUE TITLE
[noetic] image_transport_plugins 1.15.0 not released

### ISSUE THREAD

**Issue by daenny** [ros/rosdistro#42149]
I am using conda/robostack-staging to install our packages. 

I am running into issues with `params.size()` due to a new version of OpenCV (4.7+). This is actually fixed in `image_transport_plugins`  `v1.15.0`.

However, this version was released, and reverted in https://github.com/ros/rosdistro/pull/36304, but never released again. 

What is the status of this? And can this be re-released?

**Comment by daenny** [comment]
I added a PR here again:
https://github.com/ros/rosdistro/pull/42174

**Comment by mjcarroll** [comment]
Closed by #42174.  Thanks!
