### ISSUE TITLE
Virtualenv source install instructions

### ISSUE THREAD

**Issue by mikepurvis** [ros/rosdistro#5235]
Initially raised here: https://github.com/ros-infrastructure/rosdep/pull/307#issuecomment-51600827

This is especially for OS X, but would apply broadly to non-Ubuntu users who might prefer to use pip without root.

**Comment by tfoote** [comment]
I added a note that virtualenvs will protect from conflicts with system dependencies: http://wiki.ros.org/action/diff/indigo/Installation/Source?action=diff&rev1=10&rev2=11

Adding a link to an external tutorial on how to setup a virtualenv might be an improvement, but writing that tutorial is out of the scope of what we should cover in a ROS tutorial.
