### ISSUE TITLE
Missing package liburdfdom-tools in desktop full

### ISSUE THREAD

**Issue by davetcoleman** [ros/rosdistro#5956]
The ability to convert a URDF to PDF has always been part of the full ROS distro, but indigo it is not. As stated on the [wiki](http://wiki.ros.org/urdf), you now have to do an additional step:

    sudo apt-get install liburdfdom-tools

Can we instead add that to desktop-full?

**Comment by tfoote** [comment]
Closing this ticket as it has been reticketed for robot_model specifically.
