### ISSUE TITLE
geneus version downgrade

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#6723]
The version of geneus is public is 1.1.26-0 but the new version built is 0.1.0

Version number cannot go down for packages in apt. It is correctly flagged as a regression in our status page. http://www.ros.org/debbuild/indigo.html?q=regression

It needs to be released with a version number higher than previous releases. Otherwise apt will not update users installations.

**Comment by tfoote** [comment]
@k-okada this will probably break anyone using geneus

**Comment by k-okada** [comment]
sorry, I have fixed at -> https://github.com/ros/rosdistro/pull/6760

--
◉ Kei Okada
