### ISSUE TITLE
Jade: Check wiki pages

### ISSUE THREAD

**Issue by wjwwood** [ros/rosdistro#6878]
This is a list of wiki pages that I think we should look at and update for Jade if needed:

- [x] http://wiki.ros.org/actionlib_tutorials/Tutorials/RunningServerAndClientWithNodes at line 138
- [x] http://wiki.ros.org/actionlib_tutorials/Tutorials/SimpleActionClient%28Threaded%29 at line 169
- [x] http://wiki.ros.org/actionlib_tutorials/Tutorials/SimpleActionServer%28GoalCallbackMethod%29 at line 22
- [x] http://wiki.ros.org/catkin at line 3
- [x] http://wiki.ros.org/class_loader at line 4
- [x] http://wiki.ros.org/compressed_depth_image_transport at line 29
- [x] http://wiki.ros.org/compressed_image_transport at line 28
- [x] http://wiki.ros.org/costmap_2d at line 53
- [x] http://wiki.ros.org/cv_bridge/Tutorials/UsingCvBridgeToConvertBetweenROSImagesAndOpenCVImages at line 27
- [x] http://wiki.ros.org/dynamic_reconfigure/Tutorials/SettingUpDynamicReconfigureForANode%28python%29 at line 28
- [x] http://wiki.ros.org/gazebo at line 8
- [x] http://wiki.ros.org/gazebo_ros_pkgs at line 21
- [x] http://wiki.ros.org/image_proc/common at line 9
- [x] http://wiki.ros.org/image_proc/cturtle at line 9
- [x] http://wiki.ros.org/image_proc/diamondback at line 40
- [x] http://wiki.ros.org/image_proc/electric at line 67
- [x] http://wiki.ros.org/image_transport at line 112
- [x] http://wiki.ros.org/image_transport_plugins at line 7
- [x] http://wiki.ros.org/image_view/diamondback at line 182
- [x] http://wiki.ros.org/interactive_marker_twist_server at line 10
- [x] http://wiki.ros.org/mjpeg_server at line 9
- [x] http://wiki.ros.org/navigation/Tutorials/RobotSetup/TF at line 65
- [x] http://wiki.ros.org/opencv2 at line 12
- [x] http://wiki.ros.org/os/OSX/Homebrew/troubleshooting at line 28
- [x] http://wiki.ros.org/pcl/Tutorials at line 21
- [x] http://wiki.ros.org/pluginlib/pluginlib_pregroovy at line 3
- [x] http://wiki.ros.org/pluginlib/Tutorials/Writing%20and%20Using%20a%20Simple%20Plugin at line 37
- [x] http://wiki.ros.org/pluginlib at line 5
- [x] http://wiki.ros.org/ROS/Tutorials/rosdep at line 39
- [x] http://wiki.ros.org/ROS/Tutorials/SetupEnvironment at line 9
- [x] http://wiki.ros.org/rosbash at line 9
- [x] http://wiki.ros.org/rosgraph_msgs at line 15
- [x] http://wiki.ros.org/rviz/Tutorials/Librviz%3a%20Incorporating%20RViz%20into%20a%20Custom%20GUI at line 26
- [x] http://wiki.ros.org/rviz/Tutorials/Markers%3a%20Basic%20Shapes at line 134
- [x] http://wiki.ros.org/rviz/Tutorials/Plugins%3a%20New%20Display%20Type at line 26
- [x] http://wiki.ros.org/rviz/Tutorials/Plugins%3a%20New%20Dockable%20Panel at line 26
- [x] http://wiki.ros.org/rviz/Tutorials/Plugins%3a%20New%20Tool%20Type at line 26
- [x] http://wiki.ros.org/simulator_gazebo/GazeboConfiguration at line 8
- [x] http://wiki.ros.org/StackReleaseProcess at line 5
- [x] http://wiki.ros.org/stage at line 7
- [x] http://wiki.ros.org/stereo_image_proc/disparity_params at line 1
- [x] http://wiki.ros.org/StyleGuide at line 439
- [x] http://wiki.ros.org/teleop_twist_keyboard at line 11
- [x] ~~http://wiki.ros.org/test_macro at line 3~~
- [x] http://wiki.ros.org/tf/Overview/Data%20Types at line 12
- [x] http://wiki.ros.org/tf/Tutorials/Debugging%20tf%20problems at line 30
- [x] http://wiki.ros.org/tf/Tutorials/Introduction%20to%20tf at line 157
- [x] http://wiki.ros.org/tf/Tutorials/Using%20Stamped%20datatypes%20with%20tf%3a%3aMessageFilter at line 28
- [x] http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20broadcaster%20%28C%2b%2b%29 at line 68
- [x] http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20listener%20%28Python%29 at line 33
- [x] http://wiki.ros.org/theora_image_transport at line 4
- [x] ~~http://wiki.ros.org/versionexample at line 8~~
- [x] http://wiki.ros.org/visualization at line 3
- [x] http://wiki.ros.org/WikiMacros at line 16

**Comment by wjwwood** [comment]
If you are going to process a page, please check it before you start to we don't clobber each other.

**Comment by wjwwood** [comment]
@hsu or @scpeters, can one of you have a look at http://wiki.ros.org/gazebo_ros_pkgs and update it for Jade? It looks like it needs content updates, not just wiki macro touch-ups.

**Comment by scpeters** [comment]
@wjwwood We are working on it.

**Comment by wjwwood** [comment]
@esteve on http://wiki.ros.org/pluginlib the TOC doesn't show. You may need to move the TOC macro call into the included pages.

**Comment by esteve** [comment]
@wjwwood fixed.

**Comment by wjwwood** [comment]
Thanks.

**Comment by wjwwood** [comment]
Ok, I've touched up or delegated all the pages on this issue.
