### ISSUE TITLE
Documentation Audit: catkin

### ISSUE THREAD

**Issue by wjwwood** [ros/rosdistro#6946]
After touching some of our REP's I think we need to check up on our catkin documentation.

I've compiled a list of pages or sections of pages which need attention which some notes. I'll be trying to work through this as I have time.
#### REP-0140: Package.xml version 2
- [ ] http://wiki.ros.org/catkin/conceptual_overview#Dependency_Management
- [ ] http://wiki.ros.org/catkin/Tutorials/CreatingPackage
- [ ] http://wiki.ros.org/catkin/package.xml#Build.2C_Run.2C_and_Test_Dependencies
#### REP-0008: Update to Python best practices
- [ ] http://wiki.ros.org/catkin/conceptual_overview#setup.py
  - This one seems to have some incorrect information in it about dependencies, etc...
  - Maybe it should be removed and point to another resource on the `setup.py` with catkin.
- [ ] http://wiki.ros.org/catkin/migrating_from_rosbuild#Python
- [ ] http://docs.ros.org/api/catkin/html/user_guide/setup_dot_py.html
- [x] http://docs.ros.org/api/catkin/html/howto/format2/installing_python.html
- [x] http://wiki.ros.org/catkin/CMakeLists.txt#Installing_Python_Executable_Scripts
- [ ] http://wiki.ros.org/catkin#Configuration_File_References
  - This section should have a link to a page detailing the `setup.py` file and what it should contain.
- [ ] http://wiki.ros.org/catkin#REPs
  - This section should link to REP-0008.
- [ ] http://wiki.ros.org/PyStyleGuide

**Comment by wjwwood** [comment]
Checked off an item here based on https://github.com/ros/catkin/pull/769/files

**Comment by dirk-thomas** [comment]
Closing due to age and inactivity.
