### ISSUE TITLE
add verification of available release tags

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#7288]
We had a PR (#7286) which targeted a hydro package for the indigo build. This will never successfully build but it passed the automated tests. 

We should add verification of the expected build tags for the rosdistro targets in addition to the declared tags. 

We should also verify the rosdistro explicitly. The above will work implicitly since the distros have non-overlapping target architectures. 

Even better would be to check the control file for the name.

**Comment by dirk-thomas** [comment]
Closing due to age and inactivity.
