### ISSUE TITLE
rtsprofile rtctree rtshell all have downgraded in hydro

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#7429]
Same issue as #7317

The publicly available packages have higher versions than the new package. Meaning that it will not update on users machines. 

This is flagged as a regression here:
http://www.ros.org/debbuild/hydro.html?q=regression

@k-okada @130s

**Comment by 130s** [comment]
Should be fixed in https://github.com/ros/rosdistro/pull/7442, https://github.com/ros/rosdistro/pull/7441 and https://github.com/ros/rosdistro/pull/7440 by @k-okada

**Comment by tfoote** [comment]
Great thanks!
