### ISSUE TITLE
code.ros.org is down

### ISSUE THREAD

**Issue by nzjrs** [ros/rosdistro#9102]
No idea where else to file this sorry. I guessed this repository was the closet thing to distribution related....

**Comment by tfoote** [comment]
code.ros.org was announced as being End-of-life in 2013: http://lists.ros.org/pipermail/ros-users/2013-September/067953.html
It has been kept online as best as possible: http://lists.ros.org/pipermail/ros-users/2014-June/068714.html It looks like the server is completely down now, and I doubt that it will be revived again.
