### ISSUE TITLE
media-gfx/assimp is now media-libs/assimp

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros/rosdistro#9569]
https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L95
is referencing old name

**Comment by tfoote** [comment]
If you could submit a PR with the change it would be greatly appreciated. 

@allenh1 FYI

**Comment by allenh1** [comment]
Woops. I thought I fixed that one. I think media-libs/assimp is already mentioned in the yaml, so the media-gfx/assimp should just be removed.

**Comment by allenh1** [comment]
I see. Nevermind. This pull request should fix the issue. Thanks @Alessandro-Barbieri

**Comment by tfoote** [comment]
Fixed in #9571
