### ISSUE TITLE
improve eol distro detection to detect release removals

### ISSUE THREAD

**Issue by tfoote** [ros/rosdistro#9939]
Right now it parses the diff insertion block looking for the `release` entry. A removal has an empty insertion block thus does not find the `release` entry, and doesn't error. It needs to add support for parsing the removed section of the diff. 

Relevant function: https://github.com/ros/rosdistro/blob/master/test/test_url_validity.py#L135

Failed to detect in #9937

**Comment by dirk-thomas** [comment]
Closing due to age and inactivity.
